/**
 * catalogue.js — 79 hook references, read one at a time and written down.
 *
 * This is the source of truth for the whole hook system. Everything else
 * — the templates, the renderer, the shot list, the triage sheets — is
 * generated from it, so a reference described here wrongly is wrong
 * everywhere at once and a reference described right is right everywhere.
 *
 * WHAT IS RECORDED, AND WHAT IS NOT
 *
 * Recorded: the structure. Which family of layout it is, where the type
 * sits, what carries the picture, where the mark goes, and what
 * persuasive move the words make. That is analysis, and it is ours.
 *
 * Not recorded, not copied, not reproduced: the photographs, the
 * illustrations, the wordmarks and the copy. Those belong to whoever
 * made them. A template here is our own layout in our own type and
 * palette that happens to be built on the same skeleton, which is what
 * every designer has always done with a reference and is the opposite of
 * lifting the file.
 *
 * `blocked` marks the four that use a real person's face without a
 * licence — Ogilvy, Carell, Atkinson twice. The layouts are fine and are
 * kept. The faces are not ours to use and must never be shipped.
 *
 * FIELDS
 *   id        h001..h079, matching .refs/hooks/hNNN.jpg
 *   family    the layout skeleton, see FAMILIES below
 *   move      the persuasive technique the hook uses
 *   says      the reference's own words, for identification only
 *   ground    what the sheet is made of
 *   needs     what a render of this template requires from us
 *   mark      where the watermark belongs in THIS layout, specifically
 *   note      what makes it work, or what to watch
 *   blocked   set when the reference cannot be reproduced as-is
 */

/**
 * The fifteen skeletons all 79 reduce to.
 *
 * Fifteen rather than seventy-nine because that is what is actually
 * there: the same handful of structures, re-dressed. Building
 * seventy-nine one-off renderers would produce seventy-nine things that
 * cannot be recombined, and the point is a machine that makes five a day
 * for a year.
 */
export const FAMILIES = {
  field: {
    what: 'A flat colour ground and nothing but type. The whole design is the words and the space around them.',
    needs: [],
  },
  'type-as-image': {
    what: 'The type IS the picture: lines overlap, stagger, blur or fight each other. No photograph.',
    needs: [],
  },
  'photo-full': {
    what: 'A photograph fills the frame and the type sits on it, veiled only as much as the contrast needs.',
    needs: ['scene'],
  },
  'figure-cut': {
    what: 'A person cut out of their background, standing on a flat or gridded ground, with the hook above them.',
    needs: ['cutout'],
  },
  'halftone-portrait': {
    what: 'A face cropped close, screened to a coarse halftone, with display type across it.',
    needs: ['portrait'],
  },
  'object-hero': {
    what: 'One object, centred, on a plain ground. The hook sits above or below it.',
    needs: ['object'],
  },
  'collage-cutout': {
    what: 'Several cut-out objects arranged or scattered, type woven between them.',
    needs: ['objects'],
  },
  'ui-device': {
    what: 'A piece of interface — a search field, a notes app, an error dialog, a context menu — carrying the joke.',
    needs: [],
  },
  'editorial-grid': {
    what: 'A magazine page: rules, columns, micro-labels, a barcode, a date. Order as the message.',
    needs: [],
  },
  'split-block': {
    what: 'A hard horizontal split. Colour block over photograph, or the reverse.',
    needs: ['scene'],
  },
  'annotated-photo': {
    what: 'A photograph with short labels and arrows pointing into it.',
    needs: ['scene'],
  },
  'grid-tiles': {
    what: 'A ruled grid where words occupy cells, like a crossword or a board.',
    needs: [],
  },
  'numeral-hero': {
    what: 'A number is the largest thing on the sheet. Listicles and prices.',
    needs: [],
  },
  'sticker-doodle': {
    what: 'Hand-drawn scribbles, stickers and highlighter over a photograph or flat ground.',
    needs: ['scene'],
  },
  'caption-frame': {
    what: 'The sheet is framed as a screenshot or a card — a post, a note, a quote block.',
    needs: [],
  },
};

export const HOOKS = [
  { id: 'h001', family: 'halftone-portrait', move: 'provocation + clinical readout',
    says: 'lust. / body before soul / Instinct???', ground: 'newsprint paper, red rule',
    needs: ['portrait'], mark: 'in the clinical caption block, bottom left, as a data line',
    note: 'A tabloid word set huge, then undercut by a cold observational paragraph. The barcode sells the whole conceit.' },
  { id: 'h002', family: 'halftone-portrait', move: 'provocation + clinical readout',
    says: 'same sheet as h001, red colourway', ground: 'flood red, paper type',
    needs: ['portrait'], mark: 'same, bottom-left caption block',
    note: 'Proof the family takes a colourway swap with no structural change. Worth keeping both as one template with two grounds.' },
  { id: 'h003', family: 'numeral-hero', move: 'numbered promise',
    says: 'Top 108 Websites — every designer should know', ground: 'white, faint graph grid',
    needs: ['objects'], mark: 'top right, beside the arrow, as a lockup',
    note: 'The numeral does all the work. Screenshots collaged below are evidence, not decoration.' },
  { id: 'h004', family: 'photo-full', move: 'tutorial promise + swipe',
    says: 'HOW TO MAKE THIS GLASS EFFECT / SWIPE FOR MORE', ground: 'warm gradient',
    needs: ['scene'], mark: 'centred above the headline, as a small round badge',
    note: 'Header states the deliverable, panel shows the result. The swipe line is the whole call to action.' },
  { id: 'h005', family: 'photo-full', move: 'stop doing X, do Y',
    says: 'stop using pinterest for everything — instead try these websites', ground: 'photograph, acid green accent',
    needs: ['scene'], mark: 'in the top rail beside the date and the category',
    note: 'The rail across the top does a lot: it dates the post and makes it read as an issue rather than an ad.' },
  { id: 'h006', family: 'editorial-grid', move: 'curiosity gap',
    says: 'Something Weird', ground: 'white, magenta block',
    needs: ['portrait'], mark: 'top left, in the masthead position with the handle',
    note: 'Rules, micro-columns and a barcode. The halftoned figure sits on a colour block, not on the page.' },
  { id: 'h007', family: 'type-as-image', move: 'direct question',
    says: 'Are you bored yet?', ground: 'white, red question mark',
    needs: [], mark: 'bottom right, as a credit line',
    note: 'A giant punctuation mark used as the image. Blur and chromatic fringing give it depth without a photograph.' },
  { id: 'h008', family: 'object-hero', move: 'emotional direct address',
    says: 'hey can we talk? / I just don\'t feel good with how we left', ground: 'paper',
    needs: ['object'], mark: 'bottom centre, tiny, as a made-by line',
    note: 'Serif italic against a pixelated object. The mismatch of eras is the design.' },
  { id: 'h009', family: 'photo-full', move: 'claim + proof device',
    says: 'Showcasing your work online is the best way to get hired.', ground: 'photograph, sky',
    needs: ['scene'], mark: 'bottom left, small, over the photograph',
    note: 'One line is drawn as selected text with a cursor. That single device makes a flat claim feel like a fact being pointed at.' },
  { id: 'h010', family: 'collage-cutout', move: 'principle statement',
    says: 'Design with clear intent.', ground: 'slate blue, paper grain',
    needs: ['objects'], mark: 'bottom centre, as the wordmark, full width',
    note: 'Old computers cut out and floated. Serif and pixel type mixed on purpose.' },
  { id: 'h011', family: 'type-as-image', move: 'imperative warning',
    says: 'BREAK THE PATTERN TODAY OR THE LOOP WILL REPEAT TOMORROW', ground: 'flood blue',
    needs: [], mark: 'bottom rail with the date, as a credit',
    note: 'Stencil/spray type staggered across the sheet. The stagger is the pattern being broken.' },
  { id: 'h012', family: 'ui-device', move: 'named problem + evidence',
    says: 'Confusion has the highest cost per click', ground: 'cream',
    needs: ['scene'], mark: 'in the black footer bar, left, as "brought to you by"',
    note: 'A person drowning in error dialogs. The screenshot IS the argument.' },
  { id: 'h013', family: 'figure-cut', move: 'role reversal joke',
    says: 'I\'m Hiring *Clients — only serious applicants, my sanity is limited', ground: 'crumpled paper, graph grid',
    needs: ['cutout'], mark: 'bottom left corner, as a small logo lockup',
    note: 'A job ad inverted. The requirements list is where the joke lands. Strong candidate for Ashley.' },
  { id: 'h014', family: 'split-block', move: 'aphorism',
    says: 'different gets noticed.', ground: 'two-tone navy diagonal',
    needs: ['scene'], mark: 'top right, as the wordmark',
    note: 'A diagonal split, not horizontal. One lit doorway among silhouettes carries the whole idea.' },
  { id: 'h015', family: 'photo-full', move: 'how-to promise',
    says: 'How to find your CONTENT Aesthetic', ground: 'grey grain, photo bleeding bottom',
    needs: ['scene'], mark: 'bottom left, as a handle, beside "save for later"',
    note: 'Three type styles stacked: italic serif, heavy caps, red italic. The save prompt is the conversion.' },
  { id: 'h016', family: 'photo-full', move: 'relatable defeat',
    says: 'CLIENT FEEDBACK JUST TOOK ME OUT..', ground: 'sky and grass composite',
    needs: ['scene'], mark: 'bottom centre, in a pill',
    note: 'Surreal staged photograph. Outlined display type with orbit shapes. Loud and it works.' },
  { id: 'h017', family: 'object-hero', move: 'urgency / memento mori',
    says: 'CALL NOW! / tomorrow\'s not promised....', ground: 'yellow, cyan starburst',
    needs: ['object'], mark: 'none in the reference; put it in the starburst edge',
    note: 'Two-colour risograph look. Stamp type at the top, script at the bottom.' },
  { id: 'h018', family: 'object-hero', move: 'instruction + reason',
    says: 'PUT THE PHONE DOWN! And Stop Doomscrolling', ground: 'off-white paper',
    needs: ['objects'], mark: 'top right rail, as "poster by"',
    note: 'Three objects in a row, coarse halftone. Didone caps over an italic serif. Very cheap to reproduce, very high quality look.' },
  { id: 'h019', family: 'object-hero', move: 'label + definition',
    says: 'FOMO — you don\'t pick the flavor, the flavor picks you', ground: 'white',
    needs: ['object'], mark: 'none; belongs bottom right in the white space',
    note: 'Enormous white space, a single word, tiny mono captions, one saturated object at the bottom.' },
  { id: 'h020', family: 'figure-cut', move: 'permission / reassurance',
    says: 'its never to late to lock in.', ground: 'light grey',
    needs: ['cutout'], mark: 'bottom left, small',
    note: 'High-contrast black and white cut-out, bottom-anchored, type stacked above. The simplest strong template in the set.' },
  { id: 'h021', family: 'halftone-portrait', move: 'provocation',
    says: 'DON\'T TASTE. ME / DATE FATE', ground: 'photograph, heavy grain',
    needs: ['portrait'], mark: 'in the bottom caption run',
    note: 'Words scattered at different scales across a close crop. The caption run at the bottom is fragmented on purpose.' },
  { id: 'h022', family: 'photo-full', move: 'aphorism',
    says: 'GO THE EXTRA MILE, IT\'S NEVER CROWDED.', ground: 'flood orange, blurred figure',
    needs: ['scene'], mark: 'bottom centre, as the small figure itself',
    note: 'A blurred shadow rather than a photograph. Type small and hard against a huge empty field. Confidence as a design move.' },
  { id: 'h023', family: 'photo-full', move: 'balanced advice',
    says: 'work hard but, enjoy life too.', ground: 'blue sky',
    needs: ['scene'], mark: 'bottom right over the sky',
    note: 'Two weights, one line each. The subject looks out of frame, which leaves the type the whole top half.' },
  { id: 'h024', family: 'figure-cut', move: 'challenge',
    says: 'if not me then who?', ground: 'off-white',
    needs: ['cutout'], mark: 'directly under the headline as initials',
    note: 'Line-art figure rather than a photograph. Cheap to make, reads as illustration not stock.' },
  { id: 'h025', family: 'photo-full', move: 'direct question',
    says: 'WHAT ARE YOU waiting FOR?', ground: 'photograph, traffic light',
    needs: ['scene'], mark: 'none; belongs bottom right',
    note: 'The object in the photograph answers the question. Mixed roman and italic in one line.' },
  { id: 'h026', family: 'type-as-image', move: 'quoted aphorism',
    says: 'WHO YOU ARE IS DEFINED BY WHAT YOU\'RE WILLING TO STRUGGLE FOR.', ground: 'near-black',
    needs: [], mark: 'top rail with the date and the attribution',
    note: 'Red glow type on black, lines scattered down the sheet. Almost nothing on the page and it holds.' },
  { id: 'h027', family: 'field', move: 'blunt imperative',
    says: 'Be fucking authentic.', ground: 'flood red',
    needs: [], mark: 'top left, as a handle',
    note: 'The purest sheet in the set. One line, one colour, nothing else. Language is the only risk.' },
  { id: 'h028', family: 'collage-cutout', move: 'self-deprecation',
    says: 'I have no idea what im doing.', ground: 'cream',
    needs: ['objects'], mark: 'in one of the badges, bottom centre',
    note: 'Badges and stickers around a central object. Warm and funny where most of the set is cold.' },
  { id: 'h029', family: 'object-hero', move: 'relatable paralysis',
    says: 'I Should Be Doing Something Else / But I Don\'t Know What', ground: 'cream',
    needs: ['object'], mark: 'top right rail, as "poster by"',
    note: 'Flat illustration rather than a photograph. Script and slab mixed, a hand-drawn underline for emphasis.' },
  { id: 'h030', family: 'collage-cutout', move: 'trend report',
    says: 'design trends 2026', ground: 'white, scrapbook fragments',
    needs: ['portrait'], mark: 'top centre, as the handle',
    note: 'Outlined display over halftoned figures, torn paper fragments in the corners. Busy but legible.' },
  { id: 'h031', family: 'annotated-photo', move: 'recipe metaphor',
    says: 'THE RECIPE? A pinch of strategy, a lot of creativity, zero boring content', ground: 'flood red',
    needs: ['scene'], mark: 'top right, as the agency lockup',
    note: 'View-count pills scattered around the plate as the annotation. The metaphor and the proof in one image.' },
  { id: 'h032', family: 'figure-cut', move: 'myth-busting',
    says: 'The Biggest Lie About Creativity', ground: 'white, graph grid',
    needs: ['cutout'], mark: 'top centre, as the handle',
    note: 'One word highlighted in a black box with amber type. A marionette carries the meaning without a caption.' },
  { id: 'h033', family: 'collage-cutout', move: 'positioning statement',
    says: 'This *Table doesn\'t discuss #Trends. it builds Brands.', ground: 'white, graph grid',
    needs: ['objects'], mark: 'top left as the logo, plus a "Send a DM" button bottom right',
    note: 'Top-down conference table built from cut-outs. Two calls to action at the bottom, one soft one hard.' },
  { id: 'h034', family: 'ui-device', move: 'observational take',
    says: 'a notes-app screenshot over a photograph', ground: 'photograph, red curtain',
    needs: ['scene'], mark: 'none; belongs in the notes header',
    note: 'Type set as stacked white bars, exactly like the iOS Notes highlight. Instantly readable as "someone typed this".' },
  { id: 'h035', family: 'grid-tiles', move: 'direct question',
    says: 'WHY NOBODYS OBSESSED WITH YOUR BRAND YET', ground: 'red grid over cream',
    needs: ['scene'], mark: 'the top and bottom rails, repeated left and right',
    note: 'Crossword tiles. Letters in cells force a reading rhythm and slow the scroll, which is the whole point of a hook.' },
  { id: 'h036', family: 'object-hero', move: 'category claim',
    says: 'WEB DESIGN / NOT YOUR TYPICAL CREATIVE STUDIO', ground: 'light grey',
    needs: ['object'], mark: 'top centre rail, between the two index numbers',
    note: 'A CRT with the words on the screen. Enormous margin. The most restrained sheet here.' },
  { id: 'h037', family: 'ui-device', move: 'fear of invisibility',
    says: 'If Google doesn\'t suggest you, you don\'t exist.', ground: 'off-white',
    needs: [], mark: 'bottom right, in or beside the arrow button',
    note: 'An empty search field with a blinking caret. Nothing else. Straight at Ashley\'s market.' },
  { id: 'h038', family: 'caption-frame', move: 'objection + answer',
    says: '"My business gets all its clients from Instagram. Do I really need a website?" YES.', ground: 'warm grey',
    needs: ['scene'], mark: 'top centre, as "design by"',
    note: 'The objection in quotes, the answer in one italic word. A laptop showing real work as the evidence.' },
  { id: 'h039', family: 'ui-device', move: 'pun as diagnosis',
    says: 'Your BRAND Needs a Refresh', ground: 'flood red',
    needs: ['object'], mark: 'top right lockup plus a contact bar at the bottom',
    note: 'A right-click menu with Refresh highlighted. The pun is the design and it is legible in a thumbnail.' },
  { id: 'h040', family: 'sticker-doodle', move: 'jargon demystified',
    says: 'wtf is a creative direction? + why your brand needs one', ground: 'white',
    needs: [], mark: 'bottom centre, as the wordmark',
    note: 'Type on a curve, cursor and folder stickers, a pill-shaped subline. Playful without being childish.' },
  { id: 'h041', family: 'type-as-image', move: 'hypothetical restart',
    says: 'if i had to start designing from scratch [here\'s what i\'ll do]', ground: 'off-white',
    needs: [], mark: 'none; belongs bottom left under the bracket line',
    note: 'Tightly stacked heavy type with small stickers caught between the lines. The bracket line is the promise.' },
  { id: 'h042', family: 'type-as-image', move: 'resource promise',
    says: 'insanely cool HAND WRITTEN FONTS you need', ground: 'blue with a red brush stroke',
    needs: [], mark: 'bottom centre, as the handle',
    note: 'A single brush gesture behind everything. Yellow on blue is the loudest pairing in the corpus.' },
  { id: 'h043', family: 'editorial-grid', move: 'tutorial promise',
    says: 'How to Make ASCII Art', ground: 'white, faint columns',
    needs: [], mark: 'top left and right, as two handles',
    note: 'A pill-shaped category label above a Didone headline. The ASCII shape below is generated, not photographed.' },
  { id: 'h044', family: 'editorial-grid', move: 'event announcement',
    says: 'NOISE MADE VISIBLE', ground: 'black, checkerboard cut-out',
    needs: ['object'], mark: 'in the numbered index marks',
    note: 'Bilingual, numbered index marks, a transparency checkerboard used as a real texture. Dense and confident.' },
  { id: 'h045', family: 'editorial-grid', move: 'aphorism + resource',
    says: 'want to think less and do more', ground: 'black with an inset white sheet',
    needs: ['cutout'], mark: 'bottom left, beside the QR code',
    note: 'A poster photographed inside a poster. Ruled lines with micro-labels between the words.' },
  { id: 'h046', family: 'editorial-grid', move: 'principle explained',
    says: 'The Power of Simplicity', ground: 'pale blue, one blue object',
    needs: ['object'], mark: 'none; belongs in one of the four corner blocks',
    note: 'Four corner text blocks around a single enormous object. Swiss and cold, and it earns it.' },
  { id: 'h047', family: 'numeral-hero', move: 'archival index',
    says: '08 / less is more', ground: 'bone',
    needs: ['object'], mark: 'in the footer meta row with the dimensions',
    note: 'A numeral behind the object, vertical type up the right edge, a data footer. A series template, not a one-off.' },
  { id: 'h048', family: 'editorial-grid', move: 'authority quote',
    says: '"You cannot bore people into buying your product."', ground: 'cream, duotone blue',
    needs: ['portrait'], mark: 'in the three-column body, as a source line',
    blocked: 'The portrait is David Ogilvy. Use the layout; never the face.',
    note: 'Three columns of real body copy under a quote. Duotone portrait bottom-anchored. The most "grown-up" sheet here.' },
  { id: 'h049', family: 'split-block', move: 'aphorism',
    says: 'YOU MAKE THE MOTION & THE MOTION WILL MAKE YOU / MOTION', ground: 'red block over photograph',
    needs: ['scene'], mark: 'in the tiny footer meta line',
    note: 'Colour block top, photograph bottom, one enormous word bleeding off the bottom edge.' },
  { id: 'h050', family: 'annotated-photo', move: 'outcome list',
    says: 'When it\'s done right → you sound the same everywhere / decisions get faster / the team feels aligned', ground: 'photograph from above',
    needs: ['scene'], mark: 'bottom right, in the round arrow badge',
    note: 'Four benefits placed around a still figure in a blurred crowd. Arrow glyphs do the pointing. Excellent for Ashley.' },
  { id: 'h051', family: 'figure-cut', move: 'contrast aphorism',
    says: 'Talent is loud, Discipline is QUIET', ground: 'bone, inset card',
    needs: ['cutout'], mark: 'in the bottom pill row, as a version tag',
    note: 'The walking figure is masked INTO the counter of the Q. Best single idea in the corpus.' },
  { id: 'h052', family: 'type-as-image', move: 'time-saving promise',
    says: 'tools that save me 10 hours a week as a designer', ground: 'white',
    needs: [], mark: 'none; belongs bottom centre',
    note: 'Condensed heavy type, tight leading, highlighter pills and a cursor caught in the stack.' },
  { id: 'h053', family: 'object-hero', move: 'emotional address',
    says: 'You can call me anything you want', ground: 'white',
    needs: ['object'], mark: 'bottom left, as a two-line credit',
    note: 'A hanging handset against a huge white field. Right-aligned type. Restraint doing the work.' },
  { id: 'h054', family: 'collage-cutout', move: 'reframe',
    says: 'Even a Bad Day Is Just 24 HOURS', ground: 'bone, magenta duotone fragments',
    needs: ['objects'], mark: 'none; belongs in one of the tiles',
    note: 'Ransom-note blocks: each phrase in its own box, image fragments between them.' },
  { id: 'h055', family: 'collage-cutout', move: 'reframe',
    says: 'Feelings Aren\'t Facts', ground: 'off-white',
    needs: ['objects'], mark: 'in the rule under the footer line',
    note: 'Grotesque display top and bottom, duotone fragments and one object in the middle.' },
  { id: 'h056', family: 'sticker-doodle', move: 'myth-busting',
    says: 'Creativity isn\'t talent — it\'s a system. And you can learn it.', ground: 'white',
    needs: ['scene'], mark: 'in the "Part 3" sticky note',
    note: 'Sticky notes and a selection box as UI furniture. The strikethrough on "talent" is the argument.' },
  { id: 'h057', family: 'object-hero', move: 'one-word question',
    says: 'WHY?', ground: 'white',
    needs: ['object'], mark: 'in the credits block under the headline',
    note: 'Enormous letter-spaced caps, a credits block, one surreal object. Nothing wasted.' },
  { id: 'h058', family: 'object-hero', move: 'lyrical address',
    says: 'I fell for you faster than I fell apart', ground: 'peach',
    needs: ['object'], mark: 'bottom right, beside the barcode',
    note: 'Fragments of copy scattered at four corners around a halftoned object. Barcode as furniture again.' },
  { id: 'h059', family: 'type-as-image', move: 'confession',
    says: 'I do not need to buy more cool furniture and clothes to prove to my friends that I\'m creative. they do not care',
    ground: 'flood orange-red', needs: [], mark: 'none; belongs top right',
    note: 'Each phrase on its own white strip, yellow marker scribbles over them. The last line reversed out in yellow.' },
  { id: 'h060', family: 'ui-device', move: 'nonsense rhyme + offer',
    says: 'Roses are red, This: is a horse, You should take an ilovecreatives Course.', ground: 'off-white',
    needs: ['objects'], mark: 'in the browser-chrome bar at the top',
    note: 'Framed as a browser window. Objects sit inline INSIDE the sentence, in place of words.' },
  { id: 'h061', family: 'grid-tiles', move: 'perspective shift',
    says: 'EVERYTHING AROUND YOU THAT YOU CALLED LIFE WAS MADE BY PEOPLE THAT WERE NO SMARTER THAN YOU.',
    ground: 'bone, ruled grid', needs: ['objects'], mark: 'bottom left, as a URL',
    note: 'Text and images share the same grid cells. The famous Jobs line, and the layout makes it feel evidenced.' },
  { id: 'h062', family: 'collage-cutout', move: 'how-to promise',
    says: 'How to build a Brand World', ground: 'white',
    needs: ['objects'], mark: 'none; belongs bottom centre',
    note: 'Rounded image tiles scattered at angles, a hole in the middle for the type. Reads as a moodboard exploding.' },
  { id: 'h063', family: 'photo-full', move: 'overwhelm',
    says: 'no headline; a figure wired to a wall of references', ground: 'white studio',
    needs: ['scene'], mark: 'none; belongs bottom left',
    note: 'Staged photograph doing all the work. Include as a family so a strong photograph can run without type.' },
  { id: 'h064', family: 'object-hero', move: 'named problem',
    says: 'the problem with the creative economy', ground: 'bone',
    needs: ['object'], mark: 'bottom centre, under a short rule, as the wordmark',
    note: 'Serif and italic mixed in one headline, a surreal cut-out beneath, a rule and a mark to close.' },
  { id: 'h065', family: 'caption-frame', move: 'cultural thesis',
    says: 'In Big 2026, Colonial Education Still Affects the Way Nigerians Choose their Careers.',
    ground: 'orange frame, bone card', needs: ['cutout'], mark: 'top left of the card, as the handle',
    note: 'The whole sheet is a card inside a coloured frame with a window-dots header. Scale play: a small figure at the feet of a large one.' },
  { id: 'h066', family: 'annotated-photo', move: 'analogy',
    says: 'Keeping social in-house is like owning a car you barely drive.', ground: 'photograph, dark interior',
    needs: ['scene'], mark: 'none; belongs bottom centre',
    note: 'Two handwritten annotations with hand-drawn arrows. The analogy is carried entirely by the image.' },
  { id: 'h067', family: 'sticker-doodle', move: 'contrarian take',
    says: 'JUST "DESIGN" IT WITH AI. The rise of slop design and where we draw the line.',
    ground: 'white', needs: ['scene'], mark: 'top right, as the arrow',
    note: 'A blue marker underline and exclamation drawn over a staged office photograph. Scare quotes carry the tone.' },
  { id: 'h068', family: 'figure-cut', move: 'negation',
    says: 'Support is not one size fits all.', ground: 'white',
    needs: ['cutout'], mark: 'bottom centre, as a red strapline',
    note: 'Headline split top and bottom with a group cut-out between. The split is the "not".' },
  { id: 'h069', family: 'figure-cut', move: 'era progression',
    says: 'a diagonal line of figures through the decades of technology', ground: 'white',
    needs: ['cutout'], mark: 'top left and right, as two lockups',
    note: 'Figures arranged on a diagonal, each with a dated micro-label. A timeline made of people.' },
  { id: 'h070', family: 'figure-cut', move: 'principle statement',
    says: 'NO DESIGN é igual. Quando existe conceito, até o estranho faz sentido.',
    ground: 'black with a white circle', needs: ['cutout'], mark: 'bottom centre, as the handle in the rail',
    note: 'A circle vignette behind the figure, top and bottom rails with category words. One word highlighted in a box.' },
  { id: 'h071', family: 'sticker-doodle', move: 'quotation as joke',
    says: '"That\'s what she said!"', ground: 'bone',
    needs: ['cutout'], mark: 'small, over the figure, as a handle',
    blocked: 'The figure is Steve Carell as Michael Scott. Use the layout; never the face.',
    note: 'Crayon speech bubble and scribbles over a cut-out. The attribution block is set straight, which is the joke.' },
  { id: 'h072', family: 'editorial-grid', move: 'team introduction',
    says: 'meet your CLUB DIRECTORS — the visionaries', ground: 'bone, foxed paper',
    needs: ['portrait'], mark: 'in the bottom certificate block',
    note: 'Faces cropped to half and pinned to a node diagram with connecting lines. Good for a services or process slide.' },
  { id: 'h073', family: 'editorial-grid', move: 'behind the scenes',
    says: 'behind the scene — here\'s what you didn\'t see', ground: 'bone',
    needs: ['scene'], mark: 'bottom left, as the handle beside a phone number',
    note: 'Asymmetric: image top left, headline bottom right, two text blocks. Very easy to reproduce and it looks expensive.' },
  { id: 'h074', family: 'photo-full', move: 'confession + reframe',
    says: 'HAVING PEOPLE AROUND ME DOING THE SAME thing. Not a secret editing technique... Just accountability.',
    ground: 'near-black, photograph bottom', needs: ['scene'], mark: 'bottom left, as a handle over the photograph',
    note: 'Condensed orange caps with one italic serif word, then a centred serif paragraph. The underline lands the point.' },
  { id: 'h075', family: 'field', move: 'setup for a turn',
    says: 'EVERYONE CAN POST A reel. EVERYONE CAN POST A carousel.', ground: 'paper, folded',
    needs: [], mark: 'bottom left, as the handle beside "save for later"',
    note: 'Two identical lines with the last word swapped, separated by a lot of empty paper. The repetition sets up the next slide.' },
  { id: 'h076', family: 'halftone-portrait', move: 'secret promise',
    says: 'The Secret Behind Scroll-Stopping Content', ground: 'bone, magenta accent',
    needs: ['portrait'], mark: 'top right as the wordmark, plus a URL in the torn footer',
    note: 'A headline word overlapped by the image. Circled note, brush stroke, a torn paper edge at the bottom.' },
  { id: 'h077', family: 'figure-cut', move: 'named frustration',
    says: 'Clients asking for creativity without a brief?', ground: 'white, faint grid',
    needs: ['cutout'], mark: 'none; belongs in the top rule, right',
    note: 'Sticky notes stuck to a thinking figure. Rules top and bottom. A green play button as the affordance.' },
  { id: 'h078', family: 'figure-cut', move: 'diagnosis',
    says: 'WHY YOU\'RE NOT GETTING LEADS', ground: 'slate blue, graph grid',
    needs: ['cutout'], mark: 'top centre lockup plus a full contact bar at the bottom',
    blocked: 'The figure is Rowan Atkinson. Use the layout; never the face.',
    note: 'Second line reversed out of a red box. Hand-drawn arrows. Direct-response layout, and it converts.' },
  { id: 'h079', family: 'figure-cut', move: 'corrective imperative',
    says: 'Stop designing for yourself', ground: 'navy, graph grid',
    needs: ['cutout'], mark: 'top left logo, top right URL, bottom left follow, bottom right save',
    blocked: 'The figure is Rowan Atkinson. Use the layout; never the face.',
    note: 'All four corners carry a mark. The inner border frames the whole sheet.' },
];

/** Everything that needs a picture of Ashley. */
export const NEEDS_LIKENESS = HOOKS.filter(
  (h) => h.needs.includes('cutout') || h.needs.includes('portrait')
);

/** Everything that can be rendered with type and code alone. */
export const TYPE_ONLY = HOOKS.filter((h) => h.needs.length === 0);

/** The four that must never ship with the reference's face. */
export const BLOCKED = HOOKS.filter((h) => h.blocked);

export const byFamily = () => {
  const out = {};
  for (const h of HOOKS) (out[h.family] ??= []).push(h.id);
  return out;
};
