/**
 * Generated by tools/refcuts.py. Keyed cut-outs, by role.
 *
 * `origin: 'reference'` means the object was keyed out of one of the saved
 * reference sheets. It is a PLACEHOLDER: good enough to judge a composition,
 * and somebody else's photograph. Do not publish a sheet still using one.
 */

export const CUTOUTS = {
  "objects": [
    {
      "file": "objects-0.png",
      "w": 164,
      "h": 344,
      "aspect": 0.477,
      "from": "h018",
      "origin": "reference"
    },
    {
      "file": "objects-1.png",
      "w": 152,
      "h": 345,
      "aspect": 0.441,
      "from": "h018",
      "origin": "reference"
    },
    {
      "file": "objects-2.png",
      "w": 151,
      "h": 347,
      "aspect": 0.435,
      "from": "h018",
      "origin": "reference"
    }
  ],
  "object": [
    {
      "file": "object-0.png",
      "w": 395,
      "h": 592,
      "aspect": 0.667,
      "from": "h029",
      "origin": "reference"
    },
    {
      "file": "object-1.png",
      "w": 524,
      "h": 796,
      "aspect": 0.658,
      "from": "h047",
      "origin": "reference"
    },
    {
      "file": "object-2.png",
      "w": 201,
      "h": 446,
      "aspect": 0.451,
      "from": "h025",
      "origin": "reference"
    },
    {
      "file": "object-3.png",
      "w": 467,
      "h": 695,
      "aspect": 0.672,
      "from": "h039",
      "origin": "reference"
    },
    {
      "file": "object-4.png",
      "w": 371,
      "h": 443,
      "aspect": 0.837,
      "from": "h058",
      "origin": "reference"
    }
  ],
  "figure": [
    {
      "file": "figure-0.png",
      "w": 306,
      "h": 531,
      "aspect": 0.576,
      "from": "h055",
      "origin": "reference"
    },
    {
      "file": "figure-1.png",
      "w": 734,
      "h": 559,
      "aspect": 1.313,
      "from": "h076",
      "origin": "reference"
    },
    {
      "file": "figure-2.png",
      "w": 297,
      "h": 410,
      "aspect": 0.724,
      "from": "h055",
      "origin": "reference"
    },
    {
      "file": "figure-3.png",
      "w": 734,
      "h": 498,
      "aspect": 1.474,
      "from": "h012",
      "origin": "reference"
    }
  ],
  "portrait": [
    {
      "file": "portrait-0.png",
      "w": 145,
      "h": 288,
      "aspect": 0.503,
      "from": "h072",
      "origin": "reference"
    },
    {
      "file": "portrait-1.png",
      "w": 113,
      "h": 295,
      "aspect": 0.383,
      "from": "h072",
      "origin": "reference"
    },
    {
      "file": "portrait-2.png",
      "w": 101,
      "h": 284,
      "aspect": 0.356,
      "from": "h072",
      "origin": "reference"
    }
  ],
  "crowd": [
    {
      "file": "crowd-0.png",
      "w": 633,
      "h": 971,
      "aspect": 0.652,
      "from": "h069",
      "origin": "reference"
    }
  ]
};

export const cutPath = (role, n) => `/assets/cutouts/${role}/${role}-${n}.png`;
