/**
 * examples.js — three fills per layout, on three unrelated subjects.
 *
 * WHY THREE, AND WHY UNRELATED. A single worked example becomes the
 * definition. Show one fill of h018 that says "open your own site on a
 * phone" and every agent that reads it writes put your site to the test,
 * test it on a cheap phone, have you tested your site — the same post
 * forever, re-worded. Three fills on three subjects make the structure
 * the only thing they have in common, which is the thing to copy.
 *
 * These are for a person to look at and for the renderer to draw when
 * nothing else is supplied. brief() in layouts.js deliberately does NOT
 * return them: an agent gets the slot notes and writes to the structure.
 *
 * `_art` names a file only when one exists to point at. Everything else
 * draws its box and says what kind of picture belongs there, which is
 * how the shot list stays honest.
 */

export const EXAMPLES = {

  h003: [
    { _name: 'a list of sites',
      kicker: 'Top', brand: 'aadhya technotask inc.',
      hero: '108', sub: 'Websites',
      cardAlead: ['A curated', 'collection of'],
      cardAhead: ['design', 'resources.'],
      cardAfoot: 'Explore. Learn. Create.',
      cardBlist: ['Inspiration', 'Tools', 'Courses', 'Libraries', 'Templates'],
      cardCcap: ['Handpicked', 'for designers.'],
      cardDlabel: 'Featured', cardEmark: 'A',
      footer: 'EVERY DESIGNER SHOULD KNOW' },
    { _name: 'a list of checks',
      kicker: 'All', brand: 'web3ashley',
      hero: '23', sub: 'Checks',
      cardAlead: ['A short list of', 'things that break'],
      cardAhead: ['silently, and', 'expensively.'],
      cardAfoot: 'Check. Fix. Forget.',
      cardBlist: ['Forms', 'Speed', 'Listings', 'Links', 'Backups'],
      cardCcap: ['Twenty minutes,', 'once a quarter.'],
      cardDlabel: 'Start here', cardEmark: '?',
      footer: 'BEFORE YOU LAUNCH ANYTHING' },
    { _name: 'a list of questions',
      kicker: 'Every', brand: 'web3ashley',
      hero: '11', sub: 'Questions',
      cardAlead: ['The ones I ask', 'before quoting'],
      cardAhead: ['anything, to', 'anyone.'],
      cardAfoot: 'Ask. Listen. Quote.',
      cardBlist: ['Who', 'What', 'When', 'Why', 'How much'],
      cardCcap: ['Answer them and', 'the price is easy.'],
      cardDlabel: 'The brief', cardEmark: '£',
      footer: 'ASK THESE BEFORE YOU AGREE' },
  ],

  h018: [
    { _name: 'testing',
      railL: 'poster by', railR: 'web3ashley',
      head1: 'PUT IT DOWN', head2: 'AND WALK AWAY',
      turn: 'Then Come Back Cold',
      body: 'You cannot see your own work at eleven at night. You can see it fine at eight the next morning.' },
    { _name: 'quoting',
      railL: 'notes', railR: 'no. 07',
      head1: 'NAME THE PRICE', head2: 'BEFORE THE CALL',
      turn: 'Or Have It Twice',
      body: 'Every conversation that avoids the number has to happen again with the number in it.' },
    { _name: 'hiring',
      railL: 'field notes', railR: '2026',
      head1: 'HIRE THE ONE', head2: 'WHO ASKS WHY',
      turn: 'Not the One Who Nods',
      body: 'Agreement is cheap and you can buy it anywhere. The question you had not thought of is the whole job.' },
  ],

  h037: [
    { _name: 'search',
      lead: 'If Google does not suggest you,', punch: 'you do not exist.' },
    { _name: 'a menu',
      lead: 'If they cannot read it on a phone,', punch: 'they do not order.' },
    { _name: 'a reply',
      lead: 'If you answer on Monday,', punch: 'they booked on Friday.' },
  ],

  h051: [
    { _name: 'traffic',
      railL: ['Traffic does not matter.', 'Booked calls do.'],
      railR: ['Made by', 'Ashley'],
      setup: ['Traffic is loud.', 'Enquiries are'], index: '04', hero: 'QUIET',
      subhead: ['LOUD FADES.', 'BOOKED STAYS.'],
      body: 'Ads open the door. The page is what keeps anyone in the room, and the busiest sites are rarely the ones that convert.',
      cta: 'Book the hour', date: '06.03.2026',
      note: 'A working page is not exciting. It is repetitive, and it books the calls the loud one never did.',
      footer: 'You do not need the most traffic. You need the page that turns it into a call.',
      tagA: 'AUDIT.1', tagB: 'ONE HOUR' },
    { _name: 'a trade',
      railL: ['Reviews are not referrals.', 'Repeat work is.'],
      railR: ['Field note', '11'],
      setup: ['Reviews are public.', 'Referrals are'], index: '11', hero: 'PRIVATE',
      subhead: ['STARS FADE.', 'NUMBERS STAY.'],
      body: 'A five star review is read once by a stranger. A phone number passed at a kitchen table is used for years.',
      cta: 'See the checks', date: '19.02.2026',
      note: 'Nobody photographs the job that went fine. That is exactly the one that gets you the next three.',
      footer: 'Ask for the number, not the star. One of them comes back.',
      tagA: 'TRADE.2', tagB: 'REFERRAL' },
    { _name: 'writing',
      railL: ['Posting is not the work.', 'Finishing is.'],
      railR: ['Draft', '03'],
      setup: ['Ideas are cheap.', 'Finished is'], index: '03', hero: 'RARE',
      subhead: ['STARTS ARE EASY.', 'ENDINGS ARE NOT.'],
      body: 'Everyone has the idea. The difference is the fortnight after the idea stops being interesting.',
      cta: 'Read the last one', date: '02.01.2026',
      note: 'The post you nearly deleted is usually the one somebody replies to.',
      footer: 'Nobody is short of ideas. Everybody is short of finished ones.',
      tagA: 'DRAFT.3', tagB: 'SHIPPED' },
  ],

  h013: [
    { _name: 'a studio taking work',
      kicker: "I'm", head: 'Hiring', second: '*Clients',
      strap: 'Only serious applicants. My patience is limited.',
      date: ['2ND JUNE', 'TUESDAY'], rail: 'APPLY NOW',
      terms: ['Requirements:', '- Pays on time (no "next week")',
              '- Knows what they want (not "surprise me")',
              '- Never says "make the logo bigger"'],
      deadline: ['Deadline:', 'ASAP, before I find', 'a better brief'],
      foot: 'Send your budget, your idea, and one honest sentence.' },
    { _name: 'a kitchen taking bookings',
      kicker: "We're", head: 'Seeking', second: '*Regulars',
      strap: 'Walk-ins welcome. Loyalty preferred.',
      date: ['FRIDAY', 'FROM SIX'], rail: 'BOOK NOW',
      terms: ['Requirements:', '- Turns up when the table is held',
              '- Orders the thing they came for',
              '- Tells us before they stop coming'],
      deadline: ['Closing:', 'when the last', 'table goes'],
      foot: 'Two names, one time, and we hold the corner one.' },
    { _name: 'a writer taking readers',
      kicker: 'Now', head: 'Wanted', second: '*Readers',
      strap: 'No experience necessary. Attention span helpful.',
      date: ['ISSUE', 'ELEVEN'], rail: 'SUBSCRIBE',
      terms: ['Requirements:', '- Opens it the day it lands',
              '- Replies when something lands wrong',
              '- Forwards it once, to one person'],
      deadline: ['Frequency:', 'fortnightly, and', 'never at midnight'],
      foot: 'Your address, and nothing else, ever.' },
  ],

  h020: [
    { _name: 'starting late',
      kicker: 'its never too late to', head: 'lock in.' },
    { _name: 'a slow season',
      kicker: 'nobody is coming to', head: 'save it.' },
    { _name: 'a long draft',
      kicker: 'the only way out is to', head: 'finish it.' },
  ],

  h024: [
    { _name: 'ownership',
      kicker: 'if not me', head: 'then who?', mark: 'A.M.' },
    { _name: 'timing',
      kicker: 'if not now', head: 'then when?', mark: 'FIELD 09' },
    { _name: 'price',
      kicker: 'if not this', head: 'then what?', mark: 'NOTE 02' },
  ],

  h032: [
    { _name: 'creativity',
      handle: '@web3ashley',
      head: ['The', 'Biggest Lie', 'About Creativity'],
      note: '(for everyone who has been told to "just make it pop", swipe to know what they actually mean)' },
    { _name: 'pricing',
      handle: '@web3ashley',
      head: ['What', 'Cheap Work', 'Actually Costs'],
      note: '(for anyone about to accept the lowest quote, this is the bit that arrives in month four)' },
    { _name: 'reviews',
      handle: '@web3ashley',
      head: ['Why', 'Five Stars', 'Change Nothing'],
      note: '(for the shops with a perfect rating and an empty Tuesday, the number is not the problem)' },
  ],

  h068: [
    { _name: 'one size',
      head: ['Support is not'], tail: ['one size', 'fits all.'],
      strap: 'Every business breaks differently.' },
    { _name: 'audiences',
      head: ['Your audience is not'], tail: ['everyone', 'with a phone.'],
      strap: 'Narrow beats loud, every time.' },
    { _name: 'advice',
      head: ['Good advice is not'], tail: ['the same advice', 'twice.'],
      strap: 'Ask what changed since the last one.' },
  ],

  h069: [
    { _name: 'how enquiries arrived',
      brand: 'FIELD NOTES', era: '2006 — 2026',
      noteA: ['The phone book', '2006'],
      noteB: ['The first website', '2012'],
      noteC: ['The Facebook page', '2017'],
      noteD: ['The map listing', '2026'],
      close: 'It moved four times.',
      closeBody: ['Each time, the businesses that moved with it', 'kept the calls.',
                  'The ones that waited for it to come back', 'are still waiting.'] },
    { _name: 'how a kitchen filled tables',
      brand: 'SERVICE', era: 'FIVE YEARS',
      noteA: ['Walk-ins', 'Year one'],
      noteB: ['The phone', 'Year two'],
      noteC: ['The booking link', 'Year four'],
      noteD: ['The Saturday list', 'Now'],
      close: 'Nothing was replaced.',
      closeBody: ['Every route that ever worked still works.', 'They just stopped being equal.',
                  'One of them now brings four in five,', 'and it is not the one on the door.'] },
    { _name: 'how a trade got known',
      brand: 'ON THE TOOLS', era: 'A DECADE',
      noteA: ['A van and a number', '2015'],
      noteB: ['A neighbour told one', '2018'],
      noteC: ['A photo of the job', '2021'],
      noteD: ['A page that answers', '2026'],
      close: 'Word of mouth grew a URL.',
      closeBody: ['The recommendation still happens', 'at a kitchen table.',
                  'What changed is where they go', 'ten seconds afterwards.'] },
  ],

  h070: [
    { _name: 'sameness',
      tagTL: 'CONTENT', tagTR: 'STRATEGY',
      lineA: ['NO', 'DESIGN'], lineB: 'is the same.',
      column: ['When there is a', 'concept, even the', 'strange choice', 'makes sense.'],
      sticker: 'Everything speaks',
      tagBL: 'CONTENT', tagBC: '@WEB3ASHLEY', tagBR: 'STRATEGY' },
    { _name: 'quotes',
      tagTL: 'PRICING', tagTR: 'HONESTY',
      lineA: ['NO', 'QUOTE'], lineB: 'is neutral.',
      column: ['A number is an', 'argument about', 'what the work', 'is worth.'],
      sticker: 'Say it first',
      tagBL: 'PRICING', tagBC: '@WEB3ASHLEY', tagBR: 'HONESTY' },
    { _name: 'meetings',
      tagTL: 'PROCESS', tagTR: 'TIME',
      lineA: ['NO', 'MEETING'], lineB: 'is free.',
      column: ['An hour with six', 'people in it costs', 'six hours, and it', 'is never billed.'],
      sticker: 'Write it down',
      tagBL: 'PROCESS', tagBC: '@WEB3ASHLEY', tagBR: 'TIME' },
  ],

  h077: [
    { _name: 'briefs',
      head: ['Clients asking for', 'creativity without', 'a brief?'],
      body: 'Learn how to extract clear direction from clients who cannot articulate it.' },
    { _name: 'deadlines',
      head: ['Asked for it Friday', 'and briefed you', 'on Thursday?'],
      body: 'There is a way to say no to the date without saying no to the work.' },
    { _name: 'feedback',
      head: ['Getting notes that', 'only say "make it', 'more premium"?'],
      body: 'Three questions that turn a feeling into something you can actually build.' },
  ],

  h008: [
    { _name: 'a quiet enquiry line',
      w1: 'hey', w2: 'can', w3: 'we', w4: 'talk?',
      caption: 'I just do not feel good about how we left it.',
      credit: 'made by @web3ashley' },
    { _name: 'an unanswered form',
      w1: 'did', w2: 'you', w3: 'get', w4: 'that?',
      caption: 'It said thank you. It did not say to whom.',
      credit: 'made by @web3ashley' },
    { _name: 'a site nobody visits',
      w1: 'is', w2: 'anyone', w3: 'out', w4: 'there?',
      caption: 'Four hundred visits. Not one of them said anything.',
      credit: 'made by @web3ashley' },
  ],

  h017: [
    { _name: 'the phone that never rings',
      stamp: 'CALL NOW!', bubble: 'HELP!',
      foot: ["tomorrow's", 'not promised….'] },
    { _name: 'the form nobody fills',
      stamp: 'ACT FAST!', bubble: 'WHY?',
      foot: ['nobody', 'is in a hurry….'] },
    { _name: 'the offer nobody takes',
      stamp: 'LAST CHANCE!', bubble: 'AGAIN?',
      foot: ['it was also', 'the last chance….'] },
  ],

  h019: [
    { _name: 'missing out',
      head: 'FOMO',
      defL: ['YOU DO NOT PICK', 'THE FLAVOUR.'],
      defR: ['THE FLAVOUR', 'PICKS YOU.'],
      middle: ['WILL GHOST YOU', 'AFTER ONE', 'NIGHT.'],
      trail: 'SOMETHING …' },
    { _name: 'the rebrand',
      head: 'REBRAND',
      defL: ['YOU DO NOT FIX', 'THE PROBLEM.'],
      defR: ['YOU REPAINT', 'THE DOOR.'],
      middle: ['LOOKS NEW FOR', 'ABOUT SIX', 'WEEKS.'],
      trail: 'SOMETHING …' },
    { _name: 'the discount',
      head: 'SALE',
      defL: ['YOU DO NOT WIN', 'THE CUSTOMER.'],
      defR: ['YOU RENT', 'THEM ONCE.'],
      middle: ['THEY WILL WAIT', 'FOR THE NEXT', 'ONE.'],
      trail: 'SOMETHING …' },
  ],

  h029: [
    { _name: 'the unfinished site',
      over: 'I Should Be', head: 'Doing Something', after: 'Else',
      but: 'But', close: "I Don't Know What" },
    { _name: 'the quiet month',
      over: 'I Should Be', head: 'Chasing Someone', after: 'Today',
      but: 'But', close: "I Don't Know Who" },
    { _name: 'the price list',
      over: 'I Should Have', head: 'Charged More', after: 'Then',
      but: 'But', close: "I Didn't Say It" },
  ],

  h036: [
    { _name: 'a studio',
      labelL: '(00)', labelC: 'WEB3ASHLEY', labelR: '(2026)',
      face: ['WEB', 'DESIGN'],
      foot: 'NOT YOUR TYPICAL CREATIVE STUDIO' },
    { _name: 'an audit',
      labelL: '(01)', labelC: 'WEB3ASHLEY', labelR: '(2026)',
      face: ['ONE', 'HOUR'],
      foot: 'I FIND WHAT IS COSTING YOU MONEY' },
    { _name: 'a rebuild',
      labelL: '(02)', labelC: 'WEB3ASHLEY', labelR: '(2026)',
      face: ['REBUILD', 'ONCE'],
      foot: 'THEN NOBODY HAS TO TOUCH IT AGAIN' },
  ],

  h053: [
    { _name: 'a job title',
      head: ['You can', 'call me', 'anything', 'you want'],
      note: ['it is fine by me,', 'number two out of three.',
             'he says it is his favourite,', 'and I cannot disagree.'],
      credit: ['Anything You Want', 'Reality Club'] },
    { _name: 'a deadline',
      head: ['You can', 'have it', 'fast or', 'have it right'],
      note: ['both is a third price,', 'and you already knew that.',
             'pick one out loud,', 'and I will build to it.'],
      credit: ['Pick One', 'Reality Club'] },
    { _name: 'a budget',
      head: ['You can', 'spend it', 'once or', 'spend it twice'],
      note: ['the cheap one is not cheaper,', 'it is just cheaper first.',
             'the second invoice arrives', 'in about eight months.'],
      credit: ['Twice Is Dearer', 'Reality Club'] },
  ],

  h057: [
    { _name: 'a rebuild',
      head: 'WHY?',
      colA: ['WEB3ASHLEY', 'FIELD', 'NOTES'],
      colB: ['Written and built by', 'Ashley', ''],
      colC: ['06 Mar — 20 Mar 2026', 'Online, and on a phone', ''] },
    { _name: 'a price',
      head: 'HOW?',
      colA: ['WEB3ASHLEY', 'PRICING', 'NOTES'],
      colB: ['Worked out with', 'the person paying', ''],
      colC: ['Before the work starts', 'In writing, once', ''] },
    { _name: 'a delay',
      head: 'WHEN?',
      colA: ['WEB3ASHLEY', 'SCHEDULE', 'NOTES'],
      colB: ['Agreed at the start', 'Revised out loud', ''],
      colC: ['Every Friday', 'Until it is done', ''] },
  ],

  h058: [
    { _name: 'a site that stopped working',
      opening: ['and I love you but with you,', "it's heartache I breathe"],
      head: ['I fell for you', 'faster than', 'I fell apart'],
      noteR: ['I did not obliterate these walls', 'for you to come and raid my home'],
      noteL: ['and here you are, right next to me,', 'ironically, I have never felt more alone'],
      boxed: 'maybe we have had enough',
      closing: ['you said, "do not fret love', 'someday I will be my own man,',
                "I'll be free\"", 'oh, but darling, did you mean free from me?'],
      barLabel: 'autumn · niki' },
    { _name: 'a client who went quiet',
      opening: ['you approved it on Tuesday,', 'and I have not heard since'],
      head: ['I built it fast', 'so you could', 'change it slowly'],
      noteR: ['the invoice is not the problem', 'the silence is'],
      noteL: ['three follow-ups is not nagging,', 'it is the job'],
      boxed: 'one line would have been enough',
      closing: ['you said, "leave it with me,', 'I will come back Friday",',
                'and I did, and you did not,', 'and the site is still waiting.'],
      barLabel: 'field · notes' },
    { _name: 'a launch that never came',
      opening: ['it was ready in March,', 'and it is still ready'],
      head: ['We waited for', 'the right week', 'and it never came'],
      noteR: ['nothing about it improved', 'while it sat there'],
      noteL: ['every week you wait', 'is a week it earns nothing'],
      boxed: 'the right week was March',
      closing: ['you said, "after the summer,', 'when things are quieter",',
                'and things were never quieter,', 'because that is what things do.'],
      barLabel: 'spring · notes' },
  ],

  h064: [
    { _name: 'the creative economy',
      head: ['the problem', 'with the', 'creative economy'],
      mark: 'C²I' },
    { _name: 'the rebrand',
      head: ['what nobody', 'admits about', 'a rebrand'],
      mark: 'W3A' },
    { _name: 'the busy season',
      head: ['the real cost', 'of being', 'permanently busy'],
      mark: 'No. 07' },
  ],

  h004: [
    { _name: 'a glass effect',
      kicker: 'HOW TO MAKE THIS', head: 'GLASS EFFECT', swipe: 'SWIPE FOR MORE →',
      glassA: 'YOU', glassB: 'SME', code: '230' },
    { _name: 'a slow page',
      kicker: 'HOW TO FIND YOUR', head: 'SLOW PAGE', swipe: 'SWIPE FOR MORE →',
      glassA: 'FOUR', glassB: 'SECS', code: '004' },
    { _name: 'a silent form',
      kicker: 'HOW TO TEST YOUR', head: 'CONTACT FORM', swipe: 'SWIPE FOR MORE →',
      glassA: 'SENT', glassB: 'NEVER', code: '011' },
  ],

  h005: [
    { _name: 'templates',
      railL: 'MAR 2026', railC: '@WEB3ASHLEY', railR: 'WEB DESIGN',
      head1: 'stop using', head2: 'templates',
      strap: 'FOR EVERYTHING    INSTEAD    START FROM THE PAGE THAT SELLS',
      body: 'A template is somebody else\'s answer to somebody else\'s problem. Start from the one page that has to work and build outward from it.' },
    { _name: 'discounts',
      railL: 'MAR 2026', railC: '@WEB3ASHLEY', railR: 'PRICING',
      head1: 'stop using', head2: 'discounts',
      strap: 'TO WIN THE JOB    INSTEAD    CHANGE WHAT IS IN IT',
      body: 'A lower number teaches them to wait for the next lower number. A smaller scope at the same rate teaches them what an hour of yours is worth.' },
    { _name: 'stock photos',
      railL: 'MAR 2026', railC: '@WEB3ASHLEY', railR: 'CONTENT',
      head1: 'stop using', head2: 'stock photos',
      strap: 'ON YOUR OWN SITE    INSTEAD    SHOOT THE ACTUAL ROOM',
      body: 'Nobody believes the smiling team in the sunlit office. They believe the badly lit photograph of your actual counter, because it is obviously yours.' },
  ],

  h009: [
    { _name: 'a portfolio',
      head: ['Showcasing', 'your work', 'online', 'is the best way', 'to get hired.'] },
    { _name: 'answering fast',
      head: ['Replying inside', 'the first', 'hour', 'is the whole job', 'most days.'] },
    { _name: 'saying the price',
      head: ['Putting the', 'number on', 'the page', 'saves you the calls', 'you did not want.'] },
  ],

  h015: [
    { _name: 'a content look',
      mark: '✳', line1: 'How to find your', line2: 'CONTENT', line3: 'Aesthetic',
      footL: '@web3ashley', footC: 'save for later' },
    { _name: 'a price',
      mark: '✳', line1: 'How to work out your', line2: 'DAY', line3: 'Rate',
      footL: '@web3ashley', footC: 'save for later' },
    { _name: 'a first line',
      mark: '✳', line1: 'How to write your', line2: 'OPENING', line3: 'Sentence',
      footL: '@web3ashley', footC: 'save for later' },
  ],

  h016: [
    { _name: 'feedback',
      head: ['CLIENT', 'FEEDBACK', 'JUST TOOK', 'ME OUT..'],
      handle: '@WEB3ASHLEY' },
    { _name: 'a deadline',
      head: ['THEY WANT', 'IT FRIDAY', 'AND BRIEFED', 'ME TODAY..'],
      handle: '@WEB3ASHLEY' },
    { _name: 'a budget',
      head: ['THE BUDGET', 'IS FLEXIBLE', 'THEY SAID', 'IN JANUARY..'],
      handle: '@WEB3ASHLEY' },
  ],

  h022: [
    { _name: 'effort',
      head: ['GO THE', 'EXTRA MILE,', "IT'S NEVER", 'CROWDED.'] },
    { _name: 'replying',
      head: ['ANSWER IT', 'TODAY,', 'NOBODY ELSE', 'IS GOING TO.'] },
    { _name: 'finishing',
      head: ['FINISH ONE', 'THING,', 'IT BEATS', 'STARTING SIX.'] },
  ],

  h023: [
    { _name: 'balance',
      kicker: 'work hard but,', head: 'enjoy life too.' },
    { _name: 'shipping',
      kicker: 'plan it well but,', head: 'launch it anyway.' },
    { _name: 'listening',
      kicker: 'hear them out but,', head: 'build what works.' },
  ],

  h025: [
    { _name: 'waiting',
      head: ['WHAT ARE', 'YOU waiting', 'FOR?'] },
    { _name: 'permission',
      head: ['WHO ARE', 'YOU asking', 'FIRST?'] },
    { _name: 'the right week',
      head: ['WHICH WEEK', 'IS ever', 'QUIETER?'] },
  ],

  h063: [
    { _name: 'too much input',
      caption: 'day four of the research phase' },
    { _name: 'references',
      caption: 'the mood board is now larger than the project' },
    { _name: 'competitors',
      caption: 'I have looked at forty of these and learned nothing' },
  ],

  h074: [
    { _name: 'accountability',
      head: ['HAVING PEOPLE', 'AROUND ME DOING', 'THE SAME thing.'],
      body: ['Not a secret editing technique. Not a posting',
             'hack… Just accountability. Someone to say',
             '"did you post today?"'],
      handle: '@web3ashley' },
    { _name: 'a deadline that is real',
      head: ['HAVING SOMEBODY', 'ELSE WAITING ON', 'THE same date.'],
      body: ['Not a project tool. Not a better calendar…',
             'Just one person who notices. Someone to ask',
             '"is it going out Friday?"'],
      handle: '@web3ashley' },
    { _name: 'saying it out loud',
      head: ['TELLING ONE', 'PERSON WHAT I AM', 'ACTUALLY doing.'],
      body: ['Not a strategy document. Not a rebrand…',
             'Just one sentence said to a human. Someone to say',
             '"so what is it, then?"'],
      handle: '@web3ashley' },
  ],

  h006: [
    { _name: 'a page that loads slowly',
      railL: 'instagram', railLsub: '@web3ashley', railR: '©2026',
      head: 'Something Weird',
      colA: ['some info', 'Recorded on a mid-range handset over mobile data, which is most of the traffic.'],
      colB: ['what happened', 'Time to first paint 4.1s. Time to anything readable 6.8s.'],
      colC: ['the finding', 'Nothing on the page is broken. Everything on it is late.'],
      colD: 'typography.',
      tagA: '08/06/ made with love',
      strip: ['Nobody files a complaint about a slow page. They go back, they pick '
            + 'the next result, and the only record of it is a number in an '
            + 'analytics panel nobody opens. This sheet is that number.'] },
    { _name: 'a form that sends nowhere',
      railL: 'field notes', railLsub: '@web3ashley', railR: '©2026',
      head: 'Silent Failure',
      colA: ['some info', 'Submitted forty times over six weeks. Confirmation shown forty times.'],
      colB: ['what happened', 'Messages received: none. The provider stopped accepting mail.'],
      colC: ['the finding', 'The visitor is told it worked. You are told nothing at all.'],
      colD: 'delivery.',
      tagA: '11/02/ filed quietly',
      strip: ['That asymmetry is the whole failure, and it can run for a year '
            + 'before anybody notices, because the only person who would notice '
            + 'is the one being told everything is fine.'] },
    { _name: 'a listing nobody claimed',
      railL: 'field notes', railLsub: '@web3ashley', railR: '©2026',
      head: 'Unclaimed Entry',
      colA: ['some info', 'Opening hours wrong since 2023. Telephone number cut off.'],
      colB: ['what happened', 'Photographs: three, none of them taken by you.'],
      colC: ['the finding', 'All of it editable in ten minutes, by anyone but you.'],
      colD: 'listings.',
      tagA: '03/09/ still open',
      strip: ['It is the first thing anyone sees and the last thing anyone owns. '
            + 'Claiming it costs nothing, takes one afternoon, and is almost '
            + 'never done.'] },
  ],

  h043: [
    { _name: 'a soft shadow',
      railL: '@web3ashley', railR: 'FIELD NOTES',
      kicker: 'TUTORIAL',
      head: ['How to Make', 'a Page Feel', 'Fast'],
      colL: ['Load the thing people came for first and everything else after it. '
           + 'The order matters more than the total.'],
      colR: ['Nobody measures milliseconds. They measure whether the page did '
           + 'something while they were looking at it.'] },
    { _name: 'a price that holds',
      railL: '@web3ashley', railR: 'FIELD NOTES',
      kicker: 'TUTORIAL',
      head: ['How to Quote', 'Without', 'Discounting'],
      colL: ['Change what is in the job, never what the hour costs. One is a '
           + 'negotiation and the other is a precedent.'],
      colR: ['The number you drop once becomes the number you start from '
           + 'forever, with that client and everyone they tell.'] },
    { _name: 'a first sentence',
      railL: '@web3ashley', railR: 'FIELD NOTES',
      kicker: 'TUTORIAL',
      head: ['How to Write', 'the First', 'Sentence'],
      colL: ['Say the thing that is true and slightly awkward. Nobody stops '
           + 'for a sentence that could have opened anything.'],
      colR: ['If it would work on someone else\'s page, it is not doing '
           + 'anything on yours.'] },
  ],

  h044: [
    { _name: 'an open studio',
      railL: ['WEB3ASHLEY', 'ONE HOUR', 'ONLINE'],
      railR: ['BOOKING OPEN', 'MARCH 2026', ''],
      over: 'noise made visible',
      head: ['THE PROBLEM.', 'OUT LOUD.'],
      listing: ['ONE HOUR, ON A CALL', 'YOUR SITE, ON MY SCREEN'] },
    { _name: 'a public audit',
      railL: ['WEB3ASHLEY', 'LIVE AUDIT', 'ONLINE'],
      railR: ['FIVE PLACES', 'MARCH 2026', ''],
      over: 'in public, on purpose',
      head: ['YOUR SITE.', 'MY SCREEN.'],
      listing: ['THURSDAY, SIX O\'CLOCK', 'BRING THE URL'] },
    { _name: 'office hours',
      railL: ['WEB3ASHLEY', 'OFFICE HOURS', 'ONLINE'],
      railR: ['NO CHARGE', 'EVERY FRIDAY', ''],
      over: 'ask the awkward one',
      head: ['ONE QUESTION.', 'ONE ANSWER.'],
      listing: ['FRIDAYS, ALL AFTERNOON', 'NO PITCH, NO SLIDES'] },
  ],

  h045: [
    { _name: 'doing less',
      cardTop: ['put your name', 'below the line'],
      head: ['want', 'to', 'think', 'less', 'and', 'do', 'more'],
      free: 'free audit' },
    { _name: 'shipping',
      cardTop: ['put your site', 'below the line'],
      head: ['want', 'to', 'plan', 'less', 'and', 'launch', 'sooner'],
      free: 'free audit' },
    { _name: 'answering',
      cardTop: ['put your inbox', 'below the line'],
      head: ['want', 'to', 'chase', 'less', 'and', 'close', 'more'],
      free: 'free audit' },
  ],

  h046: [
    { _name: 'simplicity',
      noteA: ['Minimalism', 'Less is more.', 'The absence of excess.',
              'A design that does not overwhelm.'],
      noteB: ['Clarity', 'Simplicity in form.', 'Lines without unnecessary curves.',
              'Transparency in every decision.'],
      head: ['The Power', 'of Simplicity'],
      footA: ['This approach, there for one reason: to unclutter details. Every '
            + 'element counts toward the overall result. Simplicity allows us to '
            + 'maintain focus without overwhelming the senses.'],
      footB: ['In design, it is important to eliminate everything unnecessary, '
            + 'leaving only what is essential. Every element must have a clear '
            + 'purpose, and anything that does not serve it is removed.'] },
    { _name: 'one page',
      noteA: ['Focus', 'One page, one job.', 'Everything else is a distraction.',
              'A visitor who is choosing is not buying.'],
      noteB: ['Proof', 'Show the work, not the words.', 'One real photograph beats six adjectives.',
              'Names and numbers over claims.'],
      head: ['The Case for', 'One Page'],
      footA: ['Most small sites are five pages because five pages felt like a '
            + 'website. Four of them are read by nobody, and the fifth is doing '
            + 'all of the work on its own.'],
      footB: ['Find the one that people actually land on. Put everything that '
            + 'matters on it, in the order somebody deciding would want it, and '
            + 'let the others become links at the bottom.'] },
    { _name: 'one price',
      noteA: ['Plainness', 'Say the number.', 'A range is better than silence.',
              'Nobody is offended by a price.'],
      noteB: ['Nerve', 'The question comes anyway.', 'Answering it late costs a call.',
              'Answering it early filters the wrong ones out.'],
      head: ['The Case for', 'Saying It'],
      footA: ['Hiding the number does not make the work seem more valuable. It '
            + 'makes the enquiry feel like a negotiation the person has already '
            + 'started losing.'],
      footB: ['Every enquiry that arrives after the number is on the page is from '
            + 'somebody who has already decided it is worth it. That is the '
            + 'whole point of putting it there.'] },
  ],

  h072: [
    { _name: 'a studio team',
      railL: 'a.y.', railR: "'26",
      kicker: 'meet your', head: ['CLUB', 'DIRECTORS'], sub: 'the visionaries',
      nameA: ['MARK LUMENARIO', 'creative director'],
      nameB: ['CELINE VALLES', 'asst. creat. director ii'],
      nameC: ['SERNAL VILORIA', 'asst. creat. director i'],
      nameD: ['JOHN DAVID AGUILAR', 'asst. creat. director i'],
      crest: 'DIGITAL VOYAGERS CLUB' },
    { _name: 'the people on a job',
      railL: 'a.y.', railR: "'26",
      kicker: 'who builds', head: ['YOUR', 'PROJECT'], sub: 'the whole list',
      nameA: ['ASHLEY', 'design and build'],
      nameB: ['ASHLEY', 'the actual writing'],
      nameC: ['ASHLEY', 'testing on real phones'],
      nameD: ['ASHLEY', 'the call on Friday'],
      crest: 'ONE PERSON, NAMED' },
    { _name: 'the questions asked first',
      railL: 'a.y.', railR: "'26",
      kicker: 'meet the', head: ['FIRST', 'FOUR'], sub: 'the ones that matter',
      nameA: ['WHO IS IT FOR', 'and who is it not for'],
      nameB: ['WHAT HAPPENS NEXT', 'after they read it'],
      nameC: ['WHAT DOES IT COST', 'and when do they find out'],
      nameD: ['WHO MAINTAINS IT', 'in eighteen months'],
      crest: 'BEFORE ANYTHING IS DRAWN' },
  ],

  h073: [
    { _name: 'the work behind it',
      rail: 'WEB3ASHLEY',
      head: ['behind', 'the', 'scene'],
      note: ["HERE'S WHAT YOU", "DIDN'T SEE — THE TEAM,", 'THE LAUGHS, AND ALL',
             'THE HARD WORK'],
      footL: '@WEB3ASHLEY', footR: 'ashleymbaht@icloud.com' },
    { _name: 'a rebuild in progress',
      rail: 'WEB3ASHLEY',
      head: ['what', 'it looks', 'like now'],
      note: ['THE OLD SITE, THE', 'NUMBERS, THE ONE PAGE', 'DOING ALL THE WORK,',
             'AND WHAT CHANGED'],
      footL: '@WEB3ASHLEY', footR: 'ashleymbaht@icloud.com' },
    { _name: 'an hour on a call',
      rail: 'WEB3ASHLEY',
      head: ['one hour,', 'your site,', 'my screen'],
      note: ['WHAT IS COSTING YOU', 'MONEY, WHAT I WOULD', 'FIX FIRST, AND WHAT',
             'YOU CAN DO YOURSELF'],
      footL: '@WEB3ASHLEY', footR: 'ashleymbaht@icloud.com' },
  ],

  h007: [
    { _name: 'boredom',
      mark: '?', w1: 'Are', w2: 'you', w3: 'bored', w4: 'yet',
      noteA: ['Will you tell the truth so I do not have to lie?',
              'Will you tell the truth so I do not have to lie?'],
      noteB: ['And if you are feelin lonely, you should tell me',
              'Before this ends up as another memory'],
      credit: 'Designed by giovi' },
    { _name: 'a quiet month',
      mark: '?', w1: 'Was', w2: 'it', w3: 'ever', w4: 'busy',
      noteA: ['You said it goes quiet every February.',
              'You said it goes quiet every February.'],
      noteB: ['And every February you wait for March to fix it',
              'Before another quarter goes the same way'],
      credit: 'made by @web3ashley' },
    { _name: 'the price',
      mark: '!', w1: 'Say', w2: 'the', w3: 'number', w4: 'first',
      noteA: ['They are going to ask you anyway.',
              'They are going to ask you anyway.'],
      noteB: ['And the ones who leave when they hear it',
              'were never going to say yes to it later'],
      credit: 'made by @web3ashley' },
  ],

  h011: [
    { _name: 'the pattern',
      l1: 'BREAK', l2: 'THE', l3: 'PATTERN TODAY', l4: 'OR THE LOOP WILL',
      l5: 'REPEAT TOMORROW',
      railL: '21 APR 2026', railR: '@web3ashley' },
    { _name: 'the follow-up',
      l1: 'SEND', l2: 'THE', l3: 'MESSAGE NOW', l4: 'OR SPEND ALL WEEK',
      l5: 'DECIDING TO',
      railL: '21 APR 2026', railR: '@web3ashley' },
    { _name: 'the launch',
      l1: 'SHIP', l2: 'THE', l3: 'THING FRIDAY', l4: 'OR IT WILL SIT THERE',
      l5: 'UNTIL DECEMBER',
      railL: '21 APR 2026', railR: '@web3ashley' },
  ],

  h026: [
    { _name: 'what you will struggle for',
      railL: 'OSCARB—H', railC: '17 JAN 2026', railR: 'M.Manson',
      c1: ['WHO', 'YOU ARE'], c2: ['IS DEFINED BY'],
      c3: ['WHAT', "YOU'RE WILLING", 'TO STRUGGLE FOR.'] },
    { _name: 'what a business is',
      railL: 'WEB3ASHLEY', railC: '17 JAN 2026', railR: 'FIELD NOTE',
      c1: ['WHAT YOU', 'ACTUALLY SELL'], c2: ['IS DECIDED BY'],
      c3: ['WHAT PEOPLE', 'ASK YOU FOR', 'WHEN THEY ARE STUCK.'] },
    { _name: 'what a site is for',
      railL: 'WEB3ASHLEY', railC: '17 JAN 2026', railR: 'FIELD NOTE',
      c1: ['WHAT A PAGE', 'IS WORTH'], c2: ['IS MEASURED BY'],
      c3: ['WHAT SOMEBODY', 'DOES IN THE', 'TEN SECONDS AFTER IT.'] },
  ],

  h041: [
    { _name: 'free fonts',
      kicker: 'insanely cool', head: ['HAND', 'WRITTEN', 'FONTS'],
      strap: 'you need', foot: 'trust us, we gotchu', handle: '@web3ashley' },
    { _name: 'a free audit',
      kicker: 'genuinely free', head: ['ONE', 'HONEST', 'HOUR'],
      strap: 'no pitch', foot: 'bring the url, that is all', handle: '@web3ashley' },
    { _name: 'a checklist',
      kicker: 'boring but true', head: ['TEN', 'THINGS', 'TO CHECK'],
      strap: 'before launch', foot: 'takes about twenty minutes', handle: '@web3ashley' },
  ],

  h042: [
    { _name: 'starting over',
      kicker: 'BUT HOW?',
      head: ['if i had to', 'start', 'designing', 'from scratch'],
      note: "[here's what i'll do]" },
    { _name: 'pricing again',
      kicker: 'FROM ZERO?',
      head: ['if i had to', 'set', 'my prices', 'all over again'],
      note: '[here is the first thing]' },
    { _name: 'one client',
      kicker: 'ONLY ONE?',
      head: ['if i could', 'keep', 'one client', 'and drop the rest'],
      note: '[i know exactly which]' },
  ],

  h052: [
    { _name: 'tools',
      head: ['tools', 'save me', '10 hours', 'a week', 'as a', 'designer'],
      tagA: 'THAT', tagB: 'CREATIVE STACK' },
    { _name: 'templates',
      head: ['one page', 'brought me', '9 of my', '10 jobs', 'last', 'year'],
      tagA: 'NINE', tagB: 'ONE PAGE' },
    { _name: 'replying fast',
      head: ['answering', 'inside', '1 hour', 'doubled', 'my', 'bookings'],
      tagA: 'ONE', tagB: 'NOTHING ELSE CHANGED' },
  ],

  h059: [
    { _name: 'proving it',
      head: ['I do not need', 'to buy more', 'cool furniture', 'and clothes',
             'to prove', 'to my friends', 'that', "I'm creative."],
      close: ['they do not', 'care'] },
    { _name: 'the tool stack',
      head: ['I do not need', 'another app', 'or a new laptop', 'or a better',
             'chair to', 'finally start', 'the thing', 'I keep describing.'],
      close: ['it needs', 'an hour'] },
    { _name: 'the rebrand',
      head: ['You do not need', 'a new logo', 'or a new name', 'or a new colour',
             'to fix a page', 'that never', 'said what', 'you actually do.'],
      close: ['say it', 'first'] },
  ],
  h010: [
    { _name: 'old tools',
      lineA: 'Design', note: ['The future', 'is built in', 'the present.'],
      lineB: 'with', lineC: 'clear', lineD: 'intent.', mark: 'CYBERX STUDIO' },
    { _name: 'the old site',
      lineA: 'Built', note: ['Nothing about it', 'has changed', 'since 2019.'],
      lineB: 'once,', lineC: 'left', lineD: 'alone.', mark: 'WEB3 ASHLEY' },
    { _name: 'the phone book',
      lineA: 'Listed', note: ['It rang for years.', 'Then one year', 'it did not.'],
      lineB: 'once,', lineC: 'found', lineD: 'never.', mark: 'WEB3 ASHLEY' },
  ],

  h028: [
    { _name: 'not knowing',
      head: 'I have no idea', script: 'what im doing.',
      badge: ['MEMBER', 'OF THE', 'NO IDEA CLUB'],
      foot: ['Proudly making it up as we go.', 'Established under questionable circumstances.'] },
    { _name: 'the quote',
      head: 'I guessed the price', script: 'and got it wrong.',
      badge: ['MEMBER', 'OF THE', 'UNDERCHARGED'],
      foot: ['Every job teaches you the number.', 'Usually about eight months late.'] },
    { _name: 'the launch',
      head: 'I said Friday', script: 'and meant maybe.',
      badge: ['MEMBER', 'OF THE', 'SOON CLUB'],
      foot: ['It went out on the Tuesday.', 'Nobody noticed but me.'] },
  ],

  h030: [
    { _name: 'trends',
      handle: '@web3ashley', head: ['design', 'trends'], year: '2026' },
    { _name: 'excuses',
      handle: '@web3ashley', head: ['launch', 'excuses'], year: '2026' },
    { _name: 'requests',
      handle: '@web3ashley', head: ['client', 'requests'], year: '2026' },
  ],

  h033: [
    { _name: 'trends and brands',
      head: ['This Table', "doesn't discuss", '#Trends.', 'it builds Brands.'],
      centreLabel: 'Growth',
      body: ['While others chase trends, we build brands',
             'through strategy, clarity, and intentional design.',
             'Every memorable identity starts with the right conversation.'],
      ctaA: 'Stay Creative', ctaB: "Let's build together" },
    { _name: 'traffic and calls',
      head: ['This Page', 'does not chase', '#Traffic.', 'it books Calls.'],
      centreLabel: 'Booked',
      body: ['Visitors are easy and calls are not.',
             'One page, written for the person deciding,',
             'does more than five written for a crawler.'],
      ctaA: 'See the checks', ctaB: 'Book the hour' },
    { _name: 'logos and answers',
      head: ['This Studio', 'does not sell', '#Logos.', 'it sells Answers.'],
      centreLabel: 'Clarity',
      body: ['A mark is the last thing that gets made,',
             'and the first thing everybody asks for.',
             'We start with what the business is losing.'],
      ctaA: 'Send a DM', ctaB: 'Start the conversation' },
  ],

  h054: [
    { _name: 'a bad day',
      w1: 'Even a', w2: 'Bad', w3: 'Day', w4: 'Is Just', w5: '24 HOURS',
      strap: ['It ends whether you fix it or not.', 'So you may as well fix it.'] },
    { _name: 'a quiet month',
      w1: 'Even a', w2: 'Dead', w3: 'Month', w4: 'Is Only', w5: '30 DAYS',
      strap: ['The ones who kept sending things', 'had a better November.'] },
    { _name: 'a lost job',
      w1: 'One', w2: 'Lost', w3: 'Job', w4: 'Is Not', w5: 'THE YEAR',
      strap: ['You will remember it in December.', 'Nobody else will.'] },
  ],

  h055: [
    { _name: 'feelings',
      w1: 'Feelings', w2: "Aren't", w3: 'Facts',
      foot: ['feelings are not facts; they reveal what is going on inside,',
             'but they do not prove what is true outside.'] },
    { _name: 'opinions',
      w1: 'Opinions', w2: "Aren't", w3: 'Data',
      foot: ['three people said it looked dated, and none of them',
             'were ever going to buy anything from you.'] },
    { _name: 'busy',
      w1: 'Busy', w2: "Isn't", w3: 'Booked',
      foot: ['a full week of admin is still a week',
             'in which nobody paid you for anything.'] },
  ],

  h062: [
    { _name: 'brand world',
      lineA: 'How to build a', lineB: 'Brand World' },
    { _name: 'a signal',
      lineA: 'How to be the only', lineB: 'Clear Thing' },
    { _name: 'noise',
      lineA: 'How to stop making', lineB: 'More Noise' },
  ],

  h012: [
    { _name: 'confusion',
      head: ['Confusion has the', 'highest cost per click'],
      sub: 'Take full control of your brand direction',
      footL: 'BROUGHT TO YOU BY', footC: 'WEB3ASHLEY',
      footR: ['ADVERTISING', 'BRANDING', 'VISUAL STORYTELLING'] },
    { _name: 'slow pages',
      head: ['Waiting has the', 'highest bounce rate'],
      sub: 'Four seconds is most of your traffic',
      footL: 'BROUGHT TO YOU BY', footC: 'WEB3ASHLEY',
      footR: ['SPEED', 'REBUILDS', 'ONE HONEST HOUR'] },
    { _name: 'silent forms',
      head: ['Silence has the', 'highest cost of all'],
      sub: 'The form said thank you. Nobody got it',
      footL: 'BROUGHT TO YOU BY', footC: 'WEB3ASHLEY',
      footR: ['FORMS', 'DELIVERY', 'THINGS THAT ACTUALLY SEND'] },
  ],

  h034: [
    { _name: 'a name',
      chrome: '‹ Notes',
      note: ['A necessidade', 'da gente de dar', 'um nome',
             'diferente para', 'tendências que', 'sempre existiram'] },
    { _name: 'the real reason',
      chrome: '‹ Notes',
      note: ['nobody left', 'because of the', 'colours', 'they left because',
             'nothing on the page', 'answered them'] },
    { _name: 'the quote',
      chrome: '‹ Notes',
      note: ['I keep dropping', 'the number to', 'win the job', 'and then doing',
             'the job for less', 'than it costs'] },
  ],

  h039: [
    { _name: 'a refresh',
      brand: ['Digital', 'Technowiz'],
      head: ['Your', 'BRAND', 'Needs a Refresh'],
      menu: ['View', 'Sort by', 'Refresh', 'New', 'Display settings'],
      foot: ['Chat with us: 977 — 9846725002', 'www.digitaltechnowiz.com'] },
    { _name: 'a rebuild',
      brand: ['WEB3', 'ASHLEY'],
      head: ['Your', 'PAGE', 'Needs an Hour'],
      menu: ['Open', 'Duplicate', 'Rebuild', 'Rename', 'Move to bin'],
      foot: ['Book the hour: web3ashley.com/book', 'ashleymbaht@icloud.com'] },
    { _name: 'a price',
      brand: ['WEB3', 'ASHLEY'],
      head: ['Your', 'QUOTE', 'Needs a Number'],
      menu: ['Draft', 'Estimate', 'Say it', 'Delay', 'Discuss later'],
      foot: ['Book the hour: web3ashley.com/book', 'ashleymbaht@icloud.com'] },
  ],

  h060: [
    { _name: 'a course',
      urlL: 'ilovecreatives', urlR: 'Courses for Creatives',
      head: ['Roses are red,', 'This:', 'is a horse,', 'You should',
             'take an', 'ilovecreatives Course.'],
      foot: 'Check them out on our site! →' },
    { _name: 'an audit',
      urlL: 'web3ashley', urlR: 'One honest hour',
      head: ['Roses are red,', 'This:', 'is a chair,', 'Your site is',
             'losing money', 'and I will show you where.'],
      foot: 'Book the hour on the site →' },
    { _name: 'a newsletter',
      urlL: 'web3ashley', urlR: 'Field notes',
      head: ['Violets are blue,', 'Also:', 'this is a lamp,', 'I send one',
             'email a fortnight', 'and it is actually good.'],
      foot: 'Put your address in the box →' },
  ],
};

/** The first example, which is what the renderer draws by default. */
export const sample = (id) => EXAMPLES[id]?.[0] ?? {};

/** All of them, for a person comparing range. */
export const samples = (id) => EXAMPLES[id] ?? [];
