/**
 * examples.js — three fills per layout, on three unrelated subjects.
 *
 * WHY THREE, AND WHY UNRELATED. A single worked example becomes the
 * definition. Show one fill of h018 that says "open your own site on a
 * phone" and every agent that reads it writes put your site to the test,
 * test it on a cheap phone, have you tested your site — the same post
 * forever, re-worded. Three fills on three subjects make the structure
 * the only thing they have in common, which is the thing to copy.
 *
 * These are for a person to look at and for the renderer to draw when
 * nothing else is supplied. brief() in layouts.js deliberately does NOT
 * return them: an agent gets the slot notes and writes to the structure.
 *
 * `_art` names a file only when one exists to point at. Everything else
 * draws its box and says what kind of picture belongs there, which is
 * how the shot list stays honest.
 */

export const EXAMPLES = {

  h001: [
    { _name: 'speed',
      head: 'gone.', mid: 'speed before style', script: 'Latency', third: 'Eleven???',
      body: ['Observed: elevated exit rate at first paint.',
             'Subject displays repeated back gestures.',
             'No complaint is filed. No record is kept.'],
      stamp: '/// EXIT: 187% ABOVE BASELINE ///' },
    { _name: 'a kitchen at close',
      head: 'cold.', mid: 'orders before covers', script: 'Ticket', third: 'Again???',
      body: ['Observed: pass holds four plates at once.',
             'Subject reheats rather than refires.',
             'Nobody at the table is told.'],
      stamp: '/// RETURNS: 3 OF 40 TONIGHT ///' },
    { _name: 'a gym in february',
      head: 'quiet.', mid: 'January before March', script: 'Attrition', third: 'Where???',
      body: ['Observed: 71 of 300 cards still active.',
             'Subject cancels without notice.',
             'The direct debit runs one more month.'],
      stamp: '/// LAPSE: 76% BY WEEK NINE ///' },
  ],

  h002: [
    { _name: 'speed, red',
      head: 'gone.', mid: 'speed before style', script: 'Latency', third: 'Eleven???',
      body: ['Observed: elevated exit rate at first paint.',
             'Subject displays repeated back gestures.',
             'No complaint is filed. No record is kept.'],
      stamp: '/// EXIT: 187% ABOVE BASELINE ///' },
  ],

  h018: [
    { _name: 'testing',
      railL: 'poster by', railR: 'web3ashley',
      head1: 'PUT IT DOWN', head2: 'AND WALK AWAY',
      turn: 'Then Come Back Cold',
      body: 'You cannot see your own work at eleven at night. You can see it fine at eight the next morning.' },
    { _name: 'quoting',
      railL: 'notes', railR: 'no. 07',
      head1: 'NAME THE PRICE', head2: 'BEFORE THE CALL',
      turn: 'Or Have It Twice',
      body: 'Every conversation that avoids the number has to happen again with the number in it.' },
    { _name: 'hiring',
      railL: 'field notes', railR: '2026',
      head1: 'HIRE THE ONE', head2: 'WHO ASKS WHY',
      turn: 'Not the One Who Nods',
      body: 'Agreement is cheap and you can buy it anywhere. The question you had not thought of is the whole job.' },
  ],

  h037: [
    { _name: 'search',
      lead: 'If Google does not suggest you,', punch: 'you do not exist.' },
    { _name: 'a menu',
      lead: 'If they cannot read it on a phone,', punch: 'they do not order.' },
    { _name: 'a reply',
      lead: 'If you answer on Monday,', punch: 'they booked on Friday.' },
  ],

  h051: [
    { _name: 'traffic',
      railL: ['Traffic does not matter.', 'Booked calls do.'],
      railR: ['Made by', 'Ashley'],
      setup: ['Traffic is loud.', 'Enquiries are'], index: '04', hero: 'QUIET',
      subhead: ['LOUD FADES.', 'BOOKED STAYS.'],
      body: 'Ads open the door. The page is what keeps anyone in the room, and the busiest sites are rarely the ones that convert.',
      cta: 'Book the hour', date: '06.03.2026',
      note: 'A working page is not exciting. It is repetitive, and it books the calls the loud one never did.',
      footer: 'You do not need the most traffic. You need the page that turns it into a call.',
      tagA: 'AUDIT.1', tagB: 'ONE HOUR' },
    { _name: 'a trade',
      railL: ['Reviews are not referrals.', 'Repeat work is.'],
      railR: ['Field note', '11'],
      setup: ['Reviews are public.', 'Referrals are'], index: '11', hero: 'PRIVATE',
      subhead: ['STARS FADE.', 'NUMBERS STAY.'],
      body: 'A five star review is read once by a stranger. A phone number passed at a kitchen table is used for years.',
      cta: 'See the checks', date: '19.02.2026',
      note: 'Nobody photographs the job that went fine. That is exactly the one that gets you the next three.',
      footer: 'Ask for the number, not the star. One of them comes back.',
      tagA: 'TRADE.2', tagB: 'REFERRAL' },
    { _name: 'writing',
      railL: ['Posting is not the work.', 'Finishing is.'],
      railR: ['Draft', '03'],
      setup: ['Ideas are cheap.', 'Finished is'], index: '03', hero: 'RARE',
      subhead: ['STARTS ARE EASY.', 'ENDINGS ARE NOT.'],
      body: 'Everyone has the idea. The difference is the fortnight after the idea stops being interesting.',
      cta: 'Read the last one', date: '02.01.2026',
      note: 'The post you nearly deleted is usually the one somebody replies to.',
      footer: 'Nobody is short of ideas. Everybody is short of finished ones.',
      tagA: 'DRAFT.3', tagB: 'SHIPPED' },
  ],

  h013: [
    { _name: 'a studio taking work',
      kicker: "I'm", head: 'Hiring', second: '*Clients',
      strap: 'Only serious applicants. My patience is limited.',
      date: ['2ND JUNE', 'TUESDAY'], rail: 'APPLY NOW',
      terms: ['Requirements:', '- Pays on time (no "next week")',
              '- Knows what they want (not "surprise me")',
              '- Never says "make the logo bigger"'],
      deadline: ['Deadline:', 'ASAP, before I find', 'a better brief'],
      foot: 'Send your budget, your idea, and one honest sentence.' },
    { _name: 'a kitchen taking bookings',
      kicker: "We're", head: 'Seeking', second: '*Regulars',
      strap: 'Walk-ins welcome. Loyalty preferred.',
      date: ['FRIDAY', 'FROM SIX'], rail: 'BOOK NOW',
      terms: ['Requirements:', '- Turns up when the table is held',
              '- Orders the thing they came for',
              '- Tells us before they stop coming'],
      deadline: ['Closing:', 'when the last', 'table goes'],
      foot: 'Two names, one time, and we hold the corner one.' },
    { _name: 'a writer taking readers',
      kicker: 'Now', head: 'Wanted', second: '*Readers',
      strap: 'No experience necessary. Attention span helpful.',
      date: ['ISSUE', 'ELEVEN'], rail: 'SUBSCRIBE',
      terms: ['Requirements:', '- Opens it the day it lands',
              '- Replies when something lands wrong',
              '- Forwards it once, to one person'],
      deadline: ['Frequency:', 'fortnightly, and', 'never at midnight'],
      foot: 'Your address, and nothing else, ever.' },
  ],

  h020: [
    { _name: 'starting late',
      kicker: 'its never too late to', head: 'lock in.' },
    { _name: 'a slow season',
      kicker: 'nobody is coming to', head: 'save it.' },
    { _name: 'a long draft',
      kicker: 'the only way out is to', head: 'finish it.' },
  ],

  h024: [
    { _name: 'ownership',
      kicker: 'if not me', head: 'then who?', mark: 'A.M.' },
    { _name: 'timing',
      kicker: 'if not now', head: 'then when?', mark: 'FIELD 09' },
    { _name: 'price',
      kicker: 'if not this', head: 'then what?', mark: 'NOTE 02' },
  ],

  h032: [
    { _name: 'creativity',
      handle: '@web3ashley',
      head: ['The', 'Biggest Lie', 'About Creativity'],
      note: '(for everyone who has been told to "just make it pop", swipe to know what they actually mean)' },
    { _name: 'pricing',
      handle: '@web3ashley',
      head: ['What', 'Cheap Work', 'Actually Costs'],
      note: '(for anyone about to accept the lowest quote, this is the bit that arrives in month four)' },
    { _name: 'reviews',
      handle: '@web3ashley',
      head: ['Why', 'Five Stars', 'Change Nothing'],
      note: '(for the shops with a perfect rating and an empty Tuesday, the number is not the problem)' },
  ],

  h068: [
    { _name: 'one size',
      head: ['Support is not'], tail: ['one size', 'fits all.'],
      strap: 'Every business breaks differently.' },
    { _name: 'audiences',
      head: ['Your audience is not'], tail: ['everyone', 'with a phone.'],
      strap: 'Narrow beats loud, every time.' },
    { _name: 'advice',
      head: ['Good advice is not'], tail: ['the same advice', 'twice.'],
      strap: 'Ask what changed since the last one.' },
  ],

  h069: [
    { _name: 'how enquiries arrived',
      brand: 'FIELD NOTES', era: '2006 — 2026',
      noteA: ['The phone book', '2006'],
      noteB: ['The first website', '2012'],
      noteC: ['The Facebook page', '2017'],
      noteD: ['The map listing', '2026'],
      close: 'It moved four times.',
      closeBody: ['Each time, the businesses that moved with it', 'kept the calls.',
                  'The ones that waited for it to come back', 'are still waiting.'] },
    { _name: 'how a kitchen filled tables',
      brand: 'SERVICE', era: 'FIVE YEARS',
      noteA: ['Walk-ins', 'Year one'],
      noteB: ['The phone', 'Year two'],
      noteC: ['The booking link', 'Year four'],
      noteD: ['The Saturday list', 'Now'],
      close: 'Nothing was replaced.',
      closeBody: ['Every route that ever worked still works.', 'They just stopped being equal.',
                  'One of them now brings four in five,', 'and it is not the one on the door.'] },
    { _name: 'how a trade got known',
      brand: 'ON THE TOOLS', era: 'A DECADE',
      noteA: ['A van and a number', '2015'],
      noteB: ['A neighbour told one', '2018'],
      noteC: ['A photo of the job', '2021'],
      noteD: ['A page that answers', '2026'],
      close: 'Word of mouth grew a URL.',
      closeBody: ['The recommendation still happens', 'at a kitchen table.',
                  'What changed is where they go', 'ten seconds afterwards.'] },
  ],

  h070: [
    { _name: 'sameness',
      tagTL: 'CONTENT', tagTR: 'STRATEGY',
      lineA: ['NO', 'DESIGN'], lineB: 'is the same.',
      column: ['When there is a', 'concept, even the', 'strange choice', 'makes sense.'],
      sticker: 'Everything speaks',
      tagBL: 'CONTENT', tagBC: '@WEB3ASHLEY', tagBR: 'STRATEGY' },
    { _name: 'quotes',
      tagTL: 'PRICING', tagTR: 'HONESTY',
      lineA: ['NO', 'QUOTE'], lineB: 'is neutral.',
      column: ['A number is an', 'argument about', 'what the work', 'is worth.'],
      sticker: 'Say it first',
      tagBL: 'PRICING', tagBC: '@WEB3ASHLEY', tagBR: 'HONESTY' },
    { _name: 'meetings',
      tagTL: 'PROCESS', tagTR: 'TIME',
      lineA: ['NO', 'MEETING'], lineB: 'is free.',
      column: ['An hour with six', 'people in it costs', 'six hours, and it', 'is never billed.'],
      sticker: 'Write it down',
      tagBL: 'PROCESS', tagBC: '@WEB3ASHLEY', tagBR: 'TIME' },
  ],

  h077: [
    { _name: 'briefs',
      head: ['Clients asking for', 'creativity without', 'a brief?'],
      body: 'Learn how to extract clear direction from clients who cannot articulate it.' },
    { _name: 'deadlines',
      head: ['Asked for it Friday', 'and briefed you', 'on Thursday?'],
      body: 'There is a way to say no to the date without saying no to the work.' },
    { _name: 'feedback',
      head: ['Getting notes that', 'only say "make it', 'more premium"?'],
      body: 'Three questions that turn a feeling into something you can actually build.' },
  ],

  h008: [
    { _name: 'a quiet enquiry line',
      w1: 'hey', w2: 'can', w3: 'we', w4: 'talk?',
      caption: 'I just do not feel good about how we left it.',
      credit: 'made by @web3ashley' },
    { _name: 'an unanswered form',
      w1: 'did', w2: 'you', w3: 'get', w4: 'that?',
      caption: 'It said thank you. It did not say to whom.',
      credit: 'made by @web3ashley' },
    { _name: 'a site nobody visits',
      w1: 'is', w2: 'anyone', w3: 'out', w4: 'there?',
      caption: 'Four hundred visits. Not one of them said anything.',
      credit: 'made by @web3ashley' },
  ],

  h017: [
    { _name: 'the phone that never rings',
      stamp: 'CALL NOW!', bubble: 'HELP!',
      foot: ["tomorrow's", 'not promised….'] },
    { _name: 'the form nobody fills',
      stamp: 'ACT FAST!', bubble: 'WHY?',
      foot: ['nobody', 'is in a hurry….'] },
    { _name: 'the offer nobody takes',
      stamp: 'LAST CHANCE!', bubble: 'AGAIN?',
      foot: ['it was also', 'the last chance….'] },
  ],

  h019: [
    { _name: 'missing out',
      head: 'FOMO',
      defL: ['YOU DO NOT PICK', 'THE FLAVOUR.'],
      defR: ['THE FLAVOUR', 'PICKS YOU.'],
      middle: ['WILL GHOST YOU', 'AFTER ONE', 'NIGHT.'],
      trail: 'SOMETHING …' },
    { _name: 'the rebrand',
      head: 'REBRAND',
      defL: ['YOU DO NOT FIX', 'THE PROBLEM.'],
      defR: ['YOU REPAINT', 'THE DOOR.'],
      middle: ['LOOKS NEW FOR', 'ABOUT SIX', 'WEEKS.'],
      trail: 'SOMETHING …' },
    { _name: 'the discount',
      head: 'SALE',
      defL: ['YOU DO NOT WIN', 'THE CUSTOMER.'],
      defR: ['YOU RENT', 'THEM ONCE.'],
      middle: ['THEY WILL WAIT', 'FOR THE NEXT', 'ONE.'],
      trail: 'SOMETHING …' },
  ],

  h029: [
    { _name: 'the unfinished site',
      over: 'I Should Be', head: 'Doing Something', after: 'Else',
      but: 'But', close: "I Don't Know What" },
    { _name: 'the quiet month',
      over: 'I Should Be', head: 'Chasing Someone', after: 'Today',
      but: 'But', close: "I Don't Know Who" },
    { _name: 'the price list',
      over: 'I Should Have', head: 'Charged More', after: 'Then',
      but: 'But', close: "I Didn't Say It" },
  ],

  h036: [
    { _name: 'a studio',
      labelL: '(00)', labelC: 'WEB3ASHLEY', labelR: '(2026)',
      face: ['WEB', 'DESIGN'],
      foot: 'NOT YOUR TYPICAL CREATIVE STUDIO' },
    { _name: 'an audit',
      labelL: '(01)', labelC: 'WEB3ASHLEY', labelR: '(2026)',
      face: ['ONE', 'HOUR'],
      foot: 'I FIND WHAT IS COSTING YOU MONEY' },
    { _name: 'a rebuild',
      labelL: '(02)', labelC: 'WEB3ASHLEY', labelR: '(2026)',
      face: ['REBUILD', 'ONCE'],
      foot: 'THEN NOBODY HAS TO TOUCH IT AGAIN' },
  ],

  h053: [
    { _name: 'a job title',
      head: ['You can', 'call me', 'anything', 'you want'],
      note: ['it is fine by me,', 'number two out of three.',
             'he says it is his favourite,', 'and I cannot disagree.'],
      credit: ['Anything You Want', 'Reality Club'] },
    { _name: 'a deadline',
      head: ['You can', 'have it', 'fast or', 'have it right'],
      note: ['both is a third price,', 'and you already knew that.',
             'pick one out loud,', 'and I will build to it.'],
      credit: ['Pick One', 'Reality Club'] },
    { _name: 'a budget',
      head: ['You can', 'spend it', 'once or', 'spend it twice'],
      note: ['the cheap one is not cheaper,', 'it is just cheaper first.',
             'the second invoice arrives', 'in about eight months.'],
      credit: ['Twice Is Dearer', 'Reality Club'] },
  ],

  h057: [
    { _name: 'a rebuild',
      head: 'WHY?',
      colA: ['WEB3ASHLEY', 'FIELD', 'NOTES'],
      colB: ['Written and built by', 'Ashley', ''],
      colC: ['06 Mar — 20 Mar 2026', 'Online, and on a phone', ''] },
    { _name: 'a price',
      head: 'HOW?',
      colA: ['WEB3ASHLEY', 'PRICING', 'NOTES'],
      colB: ['Worked out with', 'the person paying', ''],
      colC: ['Before the work starts', 'In writing, once', ''] },
    { _name: 'a delay',
      head: 'WHEN?',
      colA: ['WEB3ASHLEY', 'SCHEDULE', 'NOTES'],
      colB: ['Agreed at the start', 'Revised out loud', ''],
      colC: ['Every Friday', 'Until it is done', ''] },
  ],

  h058: [
    { _name: 'a site that stopped working',
      opening: ['and I love you but with you,', "it's heartache I breathe"],
      head: ['I fell for you', 'faster than', 'I fell apart'],
      noteR: ['I did not obliterate these walls', 'for you to come and raid my home'],
      noteL: ['and here you are, right next to me,', 'ironically, I have never felt more alone'],
      boxed: 'maybe we have had enough',
      closing: ['you said, "do not fret love', 'someday I will be my own man,',
                "I'll be free\"", 'oh, but darling, did you mean free from me?'],
      barLabel: 'autumn · niki' },
    { _name: 'a client who went quiet',
      opening: ['you approved it on Tuesday,', 'and I have not heard since'],
      head: ['I built it fast', 'so you could', 'change it slowly'],
      noteR: ['the invoice is not the problem', 'the silence is'],
      noteL: ['three follow-ups is not nagging,', 'it is the job'],
      boxed: 'one line would have been enough',
      closing: ['you said, "leave it with me,', 'I will come back Friday",',
                'and I did, and you did not,', 'and the site is still waiting.'],
      barLabel: 'field · notes' },
    { _name: 'a launch that never came',
      opening: ['it was ready in March,', 'and it is still ready'],
      head: ['We waited for', 'the right week', 'and it never came'],
      noteR: ['nothing about it improved', 'while it sat there'],
      noteL: ['every week you wait', 'is a week it earns nothing'],
      boxed: 'the right week was March',
      closing: ['you said, "after the summer,', 'when things are quieter",',
                'and things were never quieter,', 'because that is what things do.'],
      barLabel: 'spring · notes' },
  ],

  h064: [
    { _name: 'the creative economy',
      head: ['the problem', 'with the', 'creative economy'],
      mark: 'C²I' },
    { _name: 'the rebrand',
      head: ['what nobody', 'admits about', 'a rebrand'],
      mark: 'W3A' },
    { _name: 'the busy season',
      head: ['the real cost', 'of being', 'permanently busy'],
      mark: 'No. 07' },
  ],

  h004: [
    { _name: 'a slow page',
      kicker: 'HOW TO FIND YOUR', head: 'SLOW PAGE', swipe: 'SWIPE FOR MORE →' },
    { _name: 'a dead form',
      kicker: 'HOW TO TEST YOUR', head: 'CONTACT FORM', swipe: 'SWIPE FOR MORE →' },
    { _name: 'a map listing',
      kicker: 'HOW TO CLAIM YOUR', head: 'MAP LISTING', swipe: 'SWIPE FOR MORE →' },
  ],

  h005: [
    { _name: 'templates',
      railL: 'MAR 2026', railC: '@WEB3ASHLEY', railR: 'WEB DESIGN',
      head1: 'stop using', head2: 'templates',
      strap: 'FOR EVERYTHING    INSTEAD    START FROM THE PAGE THAT SELLS',
      body: 'A template is somebody else\'s answer to somebody else\'s problem. Start from the one page that has to work and build outward from it.' },
    { _name: 'discounts',
      railL: 'MAR 2026', railC: '@WEB3ASHLEY', railR: 'PRICING',
      head1: 'stop using', head2: 'discounts',
      strap: 'TO WIN THE JOB    INSTEAD    CHANGE WHAT IS IN IT',
      body: 'A lower number teaches them to wait for the next lower number. A smaller scope at the same rate teaches them what an hour of yours is worth.' },
    { _name: 'stock photos',
      railL: 'MAR 2026', railC: '@WEB3ASHLEY', railR: 'CONTENT',
      head1: 'stop using', head2: 'stock photos',
      strap: 'ON YOUR OWN SITE    INSTEAD    SHOOT THE ACTUAL ROOM',
      body: 'Nobody believes the smiling team in the sunlit office. They believe the badly lit photograph of your actual counter, because it is obviously yours.' },
  ],

  h009: [
    { _name: 'a portfolio',
      head: ['Showcasing', 'your work online', 'is the best way', 'to get hired.'] },
    { _name: 'answering fast',
      head: ['Replying inside', 'the first hour', 'is the whole job', 'most days.'] },
    { _name: 'saying the price',
      head: ['Putting the number', 'on the page', 'saves you the calls', 'you did not want.'] },
  ],

  h015: [
    { _name: 'a content look',
      mark: '✳', line1: 'How to find your', line2: 'CONTENT', line3: 'Aesthetic',
      footL: '@web3ashley', footC: 'save for later' },
    { _name: 'a price',
      mark: '✳', line1: 'How to work out your', line2: 'DAY', line3: 'Rate',
      footL: '@web3ashley', footC: 'save for later' },
    { _name: 'a first line',
      mark: '✳', line1: 'How to write your', line2: 'OPENING', line3: 'Sentence',
      footL: '@web3ashley', footC: 'save for later' },
  ],

  h016: [
    { _name: 'feedback',
      head: ['CLIENT', 'FEEDBACK', 'JUST TOOK', 'ME OUT..'],
      handle: '@WEB3ASHLEY' },
    { _name: 'a deadline',
      head: ['THEY WANT', 'IT FRIDAY', 'AND BRIEFED', 'ME TODAY..'],
      handle: '@WEB3ASHLEY' },
    { _name: 'a budget',
      head: ['THE BUDGET', 'IS FLEXIBLE', 'THEY SAID', 'IN JANUARY..'],
      handle: '@WEB3ASHLEY' },
  ],

  h022: [
    { _name: 'effort',
      head: ['GO THE', 'EXTRA MILE,', "IT'S NEVER", 'CROWDED.'] },
    { _name: 'replying',
      head: ['ANSWER IT', 'TODAY,', 'NOBODY ELSE', 'IS GOING TO.'] },
    { _name: 'finishing',
      head: ['FINISH ONE', 'THING,', 'IT BEATS', 'STARTING SIX.'] },
  ],

  h023: [
    { _name: 'balance',
      kicker: 'work hard but,', head: 'enjoy life too.' },
    { _name: 'shipping',
      kicker: 'plan it well but,', head: 'launch it anyway.' },
    { _name: 'listening',
      kicker: 'hear them out but,', head: 'build what works.' },
  ],

  h025: [
    { _name: 'waiting',
      head: ['WHAT ARE', 'YOU waiting', 'FOR?'] },
    { _name: 'permission',
      head: ['WHO ARE', 'YOU asking', 'FIRST?'] },
    { _name: 'the right week',
      head: ['WHICH WEEK', 'IS ever', 'QUIETER?'] },
  ],

  h063: [
    { _name: 'too much input',
      caption: 'day four of the research phase' },
    { _name: 'references',
      caption: 'the mood board is now larger than the project' },
    { _name: 'competitors',
      caption: 'I have looked at forty of these and learned nothing' },
  ],

  h074: [
    { _name: 'accountability',
      head: ['HAVING PEOPLE', 'AROUND ME DOING', 'THE SAME thing.'],
      body: ['Not a secret editing technique. Not a posting',
             'hack… Just accountability. Someone to say',
             '"did you post today?"'],
      handle: '@web3ashley' },
    { _name: 'a deadline that is real',
      head: ['HAVING SOMEBODY', 'ELSE WAITING ON', 'THE same date.'],
      body: ['Not a project tool. Not a better calendar…',
             'Just one person who notices. Someone to ask',
             '"is it going out Friday?"'],
      handle: '@web3ashley' },
    { _name: 'saying it out loud',
      head: ['TELLING ONE', 'PERSON WHAT I AM', 'ACTUALLY doing.'],
      body: ['Not a strategy document. Not a rebrand…',
             'Just one sentence said to a human. Someone to say',
             '"so what is it, then?"'],
      handle: '@web3ashley' },
  ],
};

/** The first example, which is what the renderer draws by default. */
export const sample = (id) => EXAMPLES[id]?.[0] ?? {};

/** All of them, for a person comparing range. */
export const samples = (id) => EXAMPLES[id] ?? [];
