/**
 * stock.js — generated by tools/fetch_stock.mjs. Do not edit.
 *
 * How many cached photographs exist per role, and where each came
 * from. Placeholders: resolveArt() prefers Ashley's own the moment
 * one is tagged for the role, and these are then unused.
 */

export const STOCK = {
  "crowd": 3,
  "object": 5,
  "objects": 5,
  "portrait": 3,
  "scene": 4
};

export const CREDITS = [
  {
    "file": "crowd-0.jpg",
    "role": "crowd",
    "by": "Camila Damásio miladamasio",
    "licence": "CC0",
    "page": "https://commons.wikimedia.org/wiki/File:Train_station_crowd_in_black_and_white_(Unsplash).jpg"
  },
  {
    "file": "crowd-1.jpg",
    "role": "crowd",
    "by": "H E N G S T R E A M hngstrm",
    "licence": "CC0",
    "page": "https://commons.wikimedia.org/wiki/File:Manners_in_Crowd_(Unsplash).jpg"
  },
  {
    "file": "crowd-2.jpg",
    "role": "crowd",
    "by": "Marvin Meyer marvelous",
    "licence": "CC0",
    "page": "https://commons.wikimedia.org/wiki/File:Looking_into_festival_crowd_(Unsplash).jpg"
  },
  {
    "file": "object-0.jpg",
    "role": "object",
    "by": "Daria Nepriakhina epicantus",
    "licence": "CC0",
    "page": "https://commons.wikimedia.org/wiki/File:Macro_rotary_phone_(Unsplash).jpg"
  },
  {
    "file": "object-1.jpg",
    "role": "object",
    "by": "meriç tuna tuna59",
    "licence": "CC0",
    "page": "https://commons.wikimedia.org/wiki/File:Harvesting_the_Wheat_Crop_(Unsplash).jpg"
  },
  {
    "file": "object-2.jpg",
    "role": "object",
    "by": "Emma Frances Logan emmafranceslogan",
    "licence": "CC0",
    "page": "https://commons.wikimedia.org/wiki/File:Turn_table_on_windowsill_(Unsplash).jpg"
  },
  {
    "file": "object-3.jpg",
    "role": "object",
    "by": "Pavan Trikutam ptrikutam",
    "licence": "CC0",
    "page": "https://commons.wikimedia.org/wiki/File:Vintage_telephone_on_the_wall._(Unsplash).jpg"
  },
  {
    "file": "object-4.jpg",
    "role": "object",
    "by": "Joshua Newton joshuanewton",
    "licence": "CC0",
    "page": "https://commons.wikimedia.org/wiki/File:Casa_Vintage,_Indonesia_(Unsplash).jpg"
  },
  {
    "file": "objects-0.jpg",
    "role": "objects",
    "by": "Alex Martinez alex_martinez",
    "licence": "CC0",
    "page": "https://commons.wikimedia.org/wiki/File:Birds_On_Wires_(Unsplash).jpg"
  },
  {
    "file": "objects-1.jpg",
    "role": "objects",
    "by": "Daria Nepriakhina epicantus",
    "licence": "CC0",
    "page": "https://commons.wikimedia.org/wiki/File:Macro_rotary_phone_(Unsplash).jpg"
  },
  {
    "file": "objects-2.jpg",
    "role": "objects",
    "by": "Clem Onojeghuo clemono2",
    "licence": "CC0",
    "page": "https://commons.wikimedia.org/wiki/File:Phoneboxes_by_the_street_(Unsplash).jpg"
  },
  {
    "file": "objects-3.jpg",
    "role": "objects",
    "by": "Jakob Owens jakobowens1",
    "licence": "CC0",
    "page": "https://commons.wikimedia.org/wiki/File:Hang_Loose_(Unsplash).jpg"
  },
  {
    "file": "objects-4.jpg",
    "role": "objects",
    "by": "Eduardo Sánchez eduardoequis",
    "licence": "CC0",
    "page": "https://commons.wikimedia.org/wiki/File:Hang_up_the_phone._(Unsplash).jpg"
  },
  {
    "file": "portrait-0.jpg",
    "role": "portrait",
    "by": "Matheus Ferrero matheusferrero",
    "licence": "CC0",
    "page": "https://commons.wikimedia.org/wiki/File:Monochrome_woman_face_glitter_(Unsplash).jpg"
  },
  {
    "file": "portrait-1.jpg",
    "role": "portrait",
    "by": "Eli DeFaria elidefaria",
    "licence": "CC0",
    "page": "https://commons.wikimedia.org/wiki/File:Woman_lying_on_concrete_(Unsplash).jpg"
  },
  {
    "file": "portrait-2.jpg",
    "role": "portrait",
    "by": "Christian Gertenbach kc_gertenbach",
    "licence": "CC0",
    "page": "https://commons.wikimedia.org/wiki/File:Portrait_of_elderly_woman_(Unsplash).jpg"
  },
  {
    "file": "scene-0.jpg",
    "role": "scene",
    "by": "Crew crew",
    "licence": "CC0",
    "page": "https://commons.wikimedia.org/wiki/File:Small_conference_room_(Unsplash).jpg"
  },
  {
    "file": "scene-1.jpg",
    "role": "scene",
    "by": "rawpixel.com rawpixel",
    "licence": "CC0",
    "page": "https://commons.wikimedia.org/wiki/File:Restaurant_Patio_Furniture_(Unsplash).jpg"
  },
  {
    "file": "scene-2.jpg",
    "role": "scene",
    "by": "Daniel von Appen daniel_von_appen",
    "licence": "CC0",
    "page": "https://commons.wikimedia.org/wiki/File:Table_and_chairs_in_Cologne_(Unsplash).jpg"
  },
  {
    "file": "scene-3.jpg",
    "role": "scene",
    "by": "Tim Gouw punttim",
    "licence": "CC0",
    "page": "https://commons.wikimedia.org/wiki/File:Busy_people_at_a_coffee_shop_(Unsplash).jpg"
  }
];
