/**
 * covers.js — generated by tools/build_covers.mjs. Do not edit.
 *
 * The slugs that have a cover drawn for them. An article not in here
 * falls back to the site card rather than pointing at a 404.
 */

export const COVERS = new Set([
  "analytics-that-actually-matter",
  "do-i-need-a-website-if-i-have-instagram",
  "google-business-profile-checklist",
  "how-much-should-a-website-cost",
  "menu-saved-as-an-image",
  "rebuild-or-repair",
  "spreadsheet-that-runs-the-business",
  "the-enquiry-form-nobody-is-reading",
  "what-delivery-apps-cost-you",
  "who-owns-your-website",
  "why-your-website-is-slow-on-mobile"
]);
