/**
 * build_covers.mjs — a cover picture for every article.
 *
 * The journal read as a bare list of headlines because that is what it
 * was: no images anywhere, on any post. A blog without pictures does not
 * feel like a blog, and the list gave a reader nothing to catch on.
 *
 * Rather than wait for photography that does not exist yet, each cover
 * is drawn from the article's own title in the site's type and palette.
 * The ground is chosen from a hash of the slug, so a post always gets
 * the same cover and two next to each other rarely match.
 *
 * They are 1200x630, which is the share-card size as well, so the same
 * file gives every article its own preview on social instead of all of
 * them falling back to the site's one card.
 *
 *   node tools/build_covers.mjs [--base http://127.0.0.1:8899]
 */
import { chromium } from 'playwright';
import fs from 'node:fs';
import path from 'node:path';

const base = process.argv.includes('--base')
  ? process.argv[process.argv.indexOf('--base') + 1]
  : 'http://127.0.0.1:8899';

const dir = 'content/articles';
const out = 'assets/covers';
fs.mkdirSync(out, { recursive: true });

const articles = fs.readdirSync(dir).filter((f) => f.endsWith('.md')).map((f) => {
  const src = fs.readFileSync(path.join(dir, f), 'utf8');
  const fm = /^---\n([\s\S]*?)\n---/.exec(src)?.[1] ?? '';
  const get = (k) => (new RegExp(`^${k}:\\s*(.+)$`, 'm').exec(fm)?.[1] ?? '').trim();
  const tags = get('tags').replace(/[[\]]/g, '').split(',').map((t) => t.trim()).filter(Boolean);
  return { slug: f.replace(/\.md$/, ''), title: get('title'), kicker: tags[0] || 'Journal' };
});

const b = await chromium.launch({
  executablePath: process.env.CHROME || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome',
});
const p = await b.newPage({ viewport: { width: 1240, height: 700 } });
const errs = [];
p.on('pageerror', (e) => errs.push(String(e)));
await p.goto(`${base}/tools/preview/cover.html`, { waitUntil: 'networkidle' });

for (const a of articles) {
  const data = await p.evaluate((x) => window.draw(x), a);
  fs.writeFileSync(path.join(out, `${a.slug}.jpg`), Buffer.from(data.split(',')[1], 'base64'));
  console.log(`  ${a.slug}.jpg`);
}
await b.close();
if (errs.length) { console.error(errs.join('\n')); process.exit(1); }

/*
 * A list of what was drawn, for the templates to check against.
 *
 * The renderer runs on the edge and cannot look at the disk, so without
 * this it pointed every article at /assets/covers/<slug>.jpg and hoped.
 * An article written in the studio after the last run of this script —
 * which is most of them, eventually — got a broken image on the card, on
 * its own page, and in every link preview. Now it falls back to the
 * site's own card instead, which is wrong-ish but not broken.
 */
const drawn = fs.readdirSync(out).filter((f) => f.endsWith('.jpg'))
  .map((f) => f.replace(/\.jpg$/, '')).sort();
fs.writeFileSync('lib/covers.js',
  '/**\n * covers.js — generated by tools/build_covers.mjs. Do not edit.\n *\n'
  + ' * The slugs that have a cover drawn for them. An article not in here\n'
  + ' * falls back to the site card rather than pointing at a 404.\n */\n\n'
  + `export const COVERS = new Set(${JSON.stringify(drawn, null, 2)});\n`);

console.log(`${articles.length} covers in ${out}, listed in lib/covers.js`);
