#!/usr/bin/env python3
"""
build_seed.py — bake the schema and seeds into lib/seed.js.

    python3 tools/build_seed.py

The studio's Set up button runs these against D1, which means a first
deploy needs no terminal at all — it can be done entirely from a phone,
with the Cloudflare dashboard for the resources and the studio for the
rest.

Re-run this whenever schema.sql or the seed scripts change.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "lib" / "seed.js"


def statements(sql: str) -> list[str]:
    """Split on the sentinel the seed scripts emit, dropping comments.

    Splitting on ';' would break every article whose body contains one, so
    the seeds mark their own boundaries.
    """
    out = []
    for chunk in sql.split("-- ==SPLIT=="):
        lines = [l for l in chunk.strip().splitlines() if not l.strip().startswith("--")]
        text = "\n".join(lines).strip()
        # D1's batch is already a transaction; its own BEGIN/COMMIT would nest
        if not text or text.upper() in ("BEGIN TRANSACTION;", "COMMIT;"):
            continue
        out.append(text)
    return out


def run(script: str) -> str:
    result = subprocess.run(
        [sys.executable, str(ROOT / "tools" / script)],
        capture_output=True, text=True, cwd=ROOT,
    )
    if result.returncode != 0:
        raise SystemExit(f"{script} failed:\n{result.stderr}")
    return result.stdout


def schema_statements() -> list[str]:
    """Comments come out before the split, not after.

    A comment can contain a semicolon — "the bytes live in R2; this is what
    the studio lists" did — and splitting first turns the tail of that
    sentence into a statement of its own.
    """
    sql = (ROOT / "schema.sql").read_text(encoding="utf-8")
    body = "\n".join(
        line for line in sql.splitlines() if not line.strip().startswith("--")
    )
    return [f"{chunk.strip()};" for chunk in body.split(";") if chunk.strip()]


def main() -> int:
    schema = schema_statements()
    seed = statements(run("seed_d1.py")) + statements(run("seed_content.py"))

    OUT.write_text(
        "/**\n"
        " * seed.js — generated by tools/build_seed.py. Do not edit.\n"
        " *\n"
        " * The schema, and the site's current content as INSERT … WHERE NOT\n"
        " * EXISTS, so applying it twice changes nothing. The studio runs these\n"
        " * on first setup, which is what lets a deployment be finished from a\n"
        " * phone with no terminal.\n"
        " */\n\n"
        f"export const SCHEMA = {json.dumps(schema, indent=2)};\n\n"
        f"export const SEED = {json.dumps(seed, indent=2)};\n",
        encoding="utf-8",
    )
    size = OUT.stat().st_size
    print(f"lib/seed.js — {len(schema)} schema statements, {len(seed)} rows, {size // 1024}KB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
