/**
 * measure_hooks.mjs — how many characters each hook slot actually holds.
 *
 *   python3 -m http.server 8899
 *   node tools/measure_hooks.mjs > assets/js/hooks/budgets.js
 *
 * Measured, not estimated. Each type slot is filled with real prose at
 * growing lengths and drawn by the real renderer; the budget is the last
 * length before `report.tight` names that slot, which is the renderer's
 * own word for "this had to shrink past its reference size".
 *
 * A `shrink` slot sets one line and shrinks to fit, so its budget is a
 * hard ceiling: one character more and the type gets smaller than the
 * sheet was designed for. A `wrap` slot flows, so its budget is the
 * whole box.
 *
 * Re-run it whenever a layout's boxes move. Nothing else may write these
 * numbers down: an estimate that disagrees with the renderer is worse
 * than no number, because Spark will believe it.
 */
import { chromium } from 'playwright';
import { CHOSEN } from '../assets/js/hooks/chosen.js';
import { LAYOUTS } from '../assets/js/hooks/layouts.js';

const base = process.env.BASE || 'http://127.0.0.1:8899';
const WORDS = ('the form on your booking page never sends anything to your inbox and '
  + 'nobody has checked it since the day it went live so the enquiries just stop')
  .split(' ');

/** Prose of about n characters, on word boundaries, so wrapping is real. */
const proseOf = (n) => {
  let out = '';
  for (let i = 0; out.length < n; i++) out += `${WORDS[i % WORDS.length]} `;
  return out.trim().slice(0, n);
};

const b = await chromium.launch({
  executablePath: process.env.CHROME || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome',
});
const p = await b.newPage({ viewport: { width: 900, height: 1000 } });
const errs = [];
p.on('pageerror', (e) => errs.push(String(e)));
await p.goto(`${base}/tools/preview/compose.html`, { waitUntil: 'networkidle' });
if (errs.length) { console.error(errs.join('\n')); await b.close(); process.exit(1); }

const fits = async (id, slotId, n) => p.evaluate(async ([i, s, text]) => {
  const r = await window.renderWith(i, { [s]: text });
  return !r.tight.includes(s);
}, [id, slotId, proseOf(n)]);

const out = {};
for (const id of CHOSEN) {
  const spec = LAYOUTS[id];
  if (!spec) continue;
  out[id] = {};
  for (const slot of spec.slots.filter((s) => s.t === 'type')) {
    // walk up until it complains, then take the last length that did not
    let last = 0;
    for (let n = 4; n <= 400; n += 4) {
      // eslint-disable-next-line no-await-in-loop
      if (!await fits(id, slot.id, n)) break;
      last = n;
    }
    out[id][slot.id] = last;
    console.error(`  ${id} ${slot.id.padEnd(10)} ${last}`);
  }
}
await b.close();

console.log(`/**
 * budgets.js — GENERATED by tools/measure_hooks.mjs. Do not edit.
 *
 * Characters each hook slot holds before the renderer has to shrink it
 * past the size the sheet was designed at. Measured against the real
 * renderer, not estimated: an estimate that disagrees with the renderer
 * is worse than no number, because it is handed to Spark as fact.
 */

export const HOOK_BUDGETS = ${JSON.stringify(out, null, 2)};
`);
