#!/usr/bin/env python3
"""
Key every usable object out of the reference sheets and file it by role.

The drawn stand-ins were the wrong answer: a drawn phone reads as an icon
and the sheets are photographic. The references themselves are full of
cleanly-shot objects on flat grounds, and those key at 0.9.

These are PLACEHOLDERS. Each one is somebody else's photograph, so a sheet
still using one must not be published; they exist so a composition can be
judged now. tools/cutouts.mjs builds the shippable library from freely
licensed sources, and resolveArt prefers it.

    python3 tools/refcuts.py
"""
from __future__ import annotations

import json
import pathlib
import shutil
import subprocess

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
WORK = pathlib.Path("/tmp/refcut")

# Assigned by looking at them. The keyer says what came out cleanly; only a
# person can say a photograph of three handsets is the `objects` role.
ASSIGN = {
    "objects":  ["h018-01", "h018-02", "h018-03"],
    "object":   ["h029-01", "h047-01", "h025-01", "h039-01",
                 "h058-01"],   # h046-01, h035-01 and h010-02 have type in them
    # h012-01 carries the reference's own three-part credit; h076-01 has a
    # word of the headline and a URL watermark burnt into it
    "figure":   ["h055-01", "h055-02"],
    "portrait": ["h072-02", "h072-03", "h072-04"],
    "crowd":    ["h069-01"],
}
# real people's faces: the catalogue refuses to ship these
# recognisable real people: never ship someone else's likeness
BLOCKED = {"h078-01", "h079-01", "h071-01", "h032-01", "h048-01"}


def main() -> int:
    shutil.rmtree(WORK, ignore_errors=True)
    subprocess.run([
        "python3", str(ROOT / "tools/extract_objects.py"), str(ROOT / ".refs/hooks"),
        "-o", str(WORK), "--min-keyability", "0.60", "--min-photographic", "0.45",
        "--min-area", "0.015", "--max-objects", "4",
    ], check=True, cwd=ROOT)

    out: dict[str, list[dict]] = {}
    for role, stems in ASSIGN.items():
        d = ROOT / f"assets/cutouts/{role}"
        d.mkdir(parents=True, exist_ok=True)
        for f in d.glob("*.png"):
            f.unlink()
        rows = []
        for i, stem in enumerate(s for s in stems if s not in BLOCKED):
            p = WORK / f"{stem}.png"
            if not p.exists():
                print(f"  missing {stem}")
                continue
            to = d / f"{role}-{i}.png"
            shutil.copy(p, to)
            im = Image.open(to)
            rows.append({"file": to.name, "w": im.width, "h": im.height,
                         "aspect": round(im.width / im.height, 3),
                         "from": stem.split("-")[0], "origin": "reference"})
        out[role] = rows

    (ROOT / "lib/hooks/cutouts.js").write_text(
        "/**\n * Generated by tools/refcuts.py. Keyed cut-outs, by role.\n *\n"
        " * `origin: 'reference'` means the object was keyed out of one of the saved\n"
        " * reference sheets. It is a PLACEHOLDER: good enough to judge a composition,\n"
        " * and somebody else's photograph. Do not publish a sheet still using one.\n */\n\n"
        f"export const CUTOUTS = {json.dumps(out, indent=2)};\n\n"
        "export const cutPath = (role, n) => `/assets/cutouts/${role}/${role}-${n}.png`;\n")
    print({k: len(v) for k, v in out.items()})
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
