#!/usr/bin/env python3
"""
seed_d1.py — turn content/articles/*.md into SQL for D1.

    python3 tools/seed_d1.py > seed.sql
    npx wrangler d1 execute web3ashley --remote --file=./seed.sql

Writes INSERT statements that skip a slug already in the table, so running
it twice adds nothing and never overwrites something edited in the studio.

This is a one-way migration. Once the articles are in D1 the studio is the
place to edit them; content/articles/ stays as the record of what was
imported, not as a second source of truth.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ARTICLES = ROOT / "content" / "articles"


def parse_front_matter(text: str) -> tuple[dict, str]:
    if not text.startswith("---"):
        raise ValueError("missing front matter")
    end = text.index("\n---", 3)
    raw, body = text[3:end], text[end + 4 :]
    meta: dict = {}
    for line in raw.strip().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, value = line.partition(":")
        value = value.strip()
        if value.startswith("[") and value.endswith("]"):
            value = ", ".join(
                v.strip().strip("\"'") for v in value[1:-1].split(",") if v.strip()
            )
        meta[key.strip()] = value.strip("\"'")
    return meta, body.lstrip("\n")


def q(value: str) -> str:
    """A SQL string literal. Doubling the quote is the whole escape."""
    return "'" + str(value).replace("'", "''") + "'"


def main() -> int:
    if not ARTICLES.exists():
        print("no content/articles directory", file=sys.stderr)
        return 1

    files = sorted(ARTICLES.glob("*.md"))
    if not files:
        print("no articles found", file=sys.stderr)
        return 1

    out = [
        "-- Generated by tools/seed_d1.py. Safe to run more than once:",
        "-- a slug already present is left exactly as it is.",
        "BEGIN TRANSACTION;",
    ]

    for path in files:
        meta, body = parse_front_matter(path.read_text(encoding="utf-8"))
        missing = [k for k in ("title", "description", "date") if k not in meta]
        if missing:
            print(f"{path.name}: missing {', '.join(missing)}", file=sys.stderr)
            return 1

        slug = meta.get("slug") or path.stem
        out.append(
            "INSERT INTO articles "
            "(slug, title, description, body, tags, status, source, published_at, created_at, updated_at)\n"
            f"SELECT {q(slug)}, {q(meta['title'])}, {q(meta['description'])}, {q(body)}, "
            f"{q(meta.get('tags', ''))}, 'published', 'import', {q(meta['date'])}, "
            f"{q(meta['date'])}, {q(meta.get('updated', meta['date']))}\n"
            f"WHERE NOT EXISTS (SELECT 1 FROM articles WHERE slug = {q(slug)});"
        )

    out.append("COMMIT;")
    print("\n".join(out))
    print(f"-- {len(files)} articles", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
