#!/usr/bin/env python3
"""
seed_content.py — put the home page's current content into D1.

    python3 tools/seed_content.py > content.sql
    npx wrangler d1 execute web3ashley --remote --file=./content.sql

Reads index.html and pulls out what the `data-cms` slots currently hold, so
the database starts life saying exactly what the page already says. Nothing
looks different the moment this runs; the difference is that afterwards it
is all editable.

Like the article seed, an existing row is left alone, so running it twice
never overwrites something edited in the studio.
"""

from __future__ import annotations

import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "index.html"


def q(value) -> str:
    return "'" + str(value).replace("'", "''") + "'"


def text_of(source: str, key: str) -> str:
    """The text currently inside a data-cms slot."""
    m = re.search(rf'data-cms="{re.escape(key)}"[^>]*>(.*?)</', source, re.S)
    if not m:
        return ""
    inner = m.group(1)
    inner = re.sub(r"<br\s*/?>", "\n", inner)
    inner = re.sub(r"<[^>]+>", "", inner)
    return html.unescape(inner).strip()


def attr_of(source: str, key: str, attr: str) -> str:
    """The value an attribute slot currently carries."""
    m = re.search(
        rf'<[^>]*{attr}="([^"]*)"[^>]*data-cms-attr="[^"]*{re.escape(attr)}:{re.escape(key)}',
        source,
    )
    if m:
        return m.group(1)
    m = re.search(
        rf'<[^>]*data-cms-attr="[^"]*{re.escape(attr)}:{re.escape(key)}[^"]*"[^>]*{attr}="([^"]*)"',
        source,
    )
    return m.group(1) if m else ""


def block_between(source: str, start_marker: str, count: int) -> list[str]:
    """The `count` sibling blocks a collection renders, first one delimited."""
    parts = source.split(start_marker)
    return parts[1:] if len(parts) > 1 else []


def main() -> int:
    if not INDEX.exists():
        print("index.html not found", file=sys.stderr)
        return 1
    s = INDEX.read_text(encoding="utf-8")

    out = [
        "-- Generated by tools/seed_content.py from the current index.html.",
        "-- Existing rows are left untouched, so this is safe to re-run.",
        "BEGIN TRANSACTION;",
    ]

    # ---------------------------------------------------------- settings ----
    settings = {
        "hero.line1": text_of(s, "hero.line1"),
        "gap.heading": text_of(s, "gap.heading"),
        "gap.statA": text_of(s, "gap.statA"),
        "gap.statALabel": text_of(s, "gap.statALabel"),
        "gap.statB": text_of(s, "gap.statB"),
        "gap.statBLabel": text_of(s, "gap.statBLabel"),
        "cta.quote": text_of(s, "cta.quote"),
        "contact.email": text_of(s, "contact.email"),
        "contact.location": text_of(s, "contact.location"),
        "contact.availability": text_of(s, "contact.availability"),
        "social.instagram": attr_of(s, "social.instagram", "href"),
        "social.tiktok": attr_of(s, "social.tiktok", "href"),
        "social.x": attr_of(s, "social.x", "href"),
        "seo.title": (re.search(r"<title>(.*?)</title>", s, re.S) or ["", ""])[1].strip(),
        "seo.description": (
            re.search(r'<meta name="description" content="([^"]*)"', s) or ["", ""]
        )[1].strip(),
        "seo.ogImage": "/assets/social/og.jpg",
    }
    for key, value in settings.items():
        if not value:
            continue
        out.append(
            f"INSERT INTO settings (key, value, updated_by) SELECT {q(key)}, {q(value)}, 'import'\n"
            f"WHERE NOT EXISTS (SELECT 1 FROM settings WHERE key = {q(key)});"
        )

    # ------------------------------------------------------- collections ----
    # Each is read from the markup the page already ships, in document order.
    def add_entries(name: str, rows: list[dict], title_field: str) -> None:
        for i, data in enumerate(rows):
            title = data.get(title_field) or f"{name}-{i + 1}"
            slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")[:70] or f"{name}-{i + 1}"
            payload = json.dumps({k: v for k, v in data.items() if v}, ensure_ascii=False)
            out.append(
                "INSERT INTO entries (collection, slug, position, status, data, author, last_editor)\n"
                f"SELECT {q(name)}, {q(slug)}, {i}, 'published', {q(payload)}, 'import', 'import'\n"
                f"WHERE NOT EXISTS (SELECT 1 FROM entries WHERE collection = {q(name)} AND slug = {q(slug)});"
            )

    # projects — the work cards
    cards = re.findall(
        r'<div role="listitem" class="works_home_item w-dyn-item">(.*?)(?=<div role="listitem" class="works_home_item w-dyn-item">|</div></div></div><div class="works_home_cta")',
        s, re.S,
    )
    projects = []
    for card in cards:
        projects.append({
            "title": re.sub(r"<[^>]+>", "", (re.search(r'class="works_home_inner_title[^"]*">(.*?)</h2>', card, re.S) or ["", ""])[1]).strip(),
            "summary": re.sub(r"<[^>]+>", "", (re.search(r'class="works_home_p[^"]*">(.*?)</p>', card, re.S) or ["", ""])[1]).strip(),
            "metric": re.sub(r"<[^>]+>", "", (re.search(r'class="works_home_result_value[^"]*">(.*?)</h3>', card, re.S) or ["", ""])[1]).strip(),
            "metricLabel": re.sub(r"<[^>]+>", "", (re.search(r'class="works_home_result_label[^"]*">(.*?)</p>', card, re.S) or ["", ""])[1]).strip(),
            "image": (re.search(r'<img src="(assets/stock/[^"]+)"', card) or ["", ""])[1],
            "clip": (re.search(r'src="(assets/stock/clip-[^"]+)"', card) or ["", ""])[1],
        })
    projects = [html_unescape_all(p) for p in projects]
    add_entries("projects", projects, "title")

    # process steps
    steps_raw = re.findall(
        r'<div role="listitem" class="process_home_content-item w-dyn-item">(.*?)(?=<div role="listitem" class="process_home_content-item w-dyn-item">|</div></div></section>)',
        s, re.S,
    )
    steps = []
    for step in steps_raw:
        steps.append(html_unescape_all({
            "heading": re.sub(r"<[^>]+>", "", (re.search(r'class="process_home_content_heading[^"]*">(.*?)</h3>', step, re.S) or ["", ""])[1]).strip(),
            "body": re.sub(r"<[^>]+>", "", (re.search(r'class="process_home_content-p[^"]*">(.*?)</p>', step, re.S) or ["", ""])[1]).strip(),
            "clip": (re.search(r'src="(assets/stock/clip-[^"]+)"', step) or ["", ""])[1],
        }))
    add_entries("steps", steps, "heading")

    # faqs
    faqs_raw = re.findall(
        r'class="accordion_css_item_heading[^"]*">(.*?)</h3>.*?class="accordion_css_bottom_rich[^"]*">(.*?)</div></div></div>',
        s, re.S,
    )
    faqs = []
    for question, answer in faqs_raw:
        body = re.sub(r"</p>\s*<p>", "\n\n", answer)
        body = re.sub(r"<[^>]+>", "", body)
        faqs.append(html_unescape_all({
            "question": re.sub(r"<[^>]+>", "", question).strip(),
            "answer": html.unescape(body).strip(),
        }))
    add_entries("faqs", faqs, "question")

    # services — the icon strip labels
    services = [
        html_unescape_all({"name": re.sub(r"<[^>]+>", "", label).strip()})
        for label in re.findall(r'class="problems_home_label">(.*?)</div>', s, re.S)
    ]
    add_entries("services", services, "name")

    out.append("COMMIT;")
    print("\n-- ==SPLIT==\n".join(out))
    print(
        f"-- settings {sum(1 for v in settings.values() if v)}, projects {len(projects)}, "
        f"steps {len(steps)}, faqs {len(faqs)}, services {len(services)}",
        file=sys.stderr,
    )
    return 0


def html_unescape_all(d: dict) -> dict:
    return {k: html.unescape(v) if isinstance(v, str) else v for k, v in d.items()}


if __name__ == "__main__":
    raise SystemExit(main())
